### ISSUE TITLE
Make sure that snuffleupagus works on any operating systems

### ISSUE THREAD

**Issue by jvoisin** [jvoisin/snuffleupagus#2]
We should leverage [GitLab CI/CD for external repositories]( https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/ ) to test Snuffleupagus in various dockers.

# Linux

- [x] Archlinux
  - [x] : We have a working [PKGBUILD](https://github.com/nbs-system/snuffleupagus/blob/master/PKGBUILD), courtesy of @xXx-caillou-xXx 
  - [x] Upstream it
- [x] AlpineLinux
  - [x]  We have a working [APKBUILD](https://github.com/nbs-system/snuffleupagus/blob/master/APKBUILD), courtesy of @xXx-caillou-xXx 
  - [x] Upstream it
- [ ] Debian/Ubuntu
  - [x] Just type `make debian`, courtesy of @jvoisin and @blotus 
  - [ ] Upstream it
  - [ ] Provide a package for debian stable when we do a release
- [ ] Red Hat stuff (@remicollet ♥)
  - [x] Fedora
  - [ ] CentOS
  - [ ] RHEL
- [ ] Gentoo (one might want to "borrow" the [suhosin ebuild]( https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-php/suhosin/suhosin-0.9.38-r1.ebuild ))
- [ ] [NixOS]( https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/php/default.nix )

# BSD

- [x] FreeBSD: Because "a lot" of people are using it, [HardenedBSD]( https://hardenedbsd.org/ ) and [OPNSense](https://opnsense.org/) are based on it.
  - We fixed a build error on FreeBSD #100 
- [ ] ~~NetBSD~~, because I don't think that anyone uses it in production to be honest :/
- [ ] OpenBSD: Since they are paranoid, they might want to use mitigations that are working, for once.

# Misc

- [ ] Windows: It would be nice to use [appveyor]( https://ci.appveyor.com ) to prove that Snuffleupagus is working on Windows. (@ylmrx)

**Comment by jvoisin** [comment]
Some magic is required to make Snuffleupagus fly on FreeBSD:

```
pkg install php71 php71-hash php71-session git
ln -s /usr/local/include/pcre.h /usr/include/pcre.h
git clone https://github.com/nbs-system/snuffleupagus
cd snuffleupagus/src
phpize
./configure --enable-snuffleupagus
# remove the `LDFLAG` line in the generated Makefile, because fbsd doesn't play nice with `-lpcre`
make
make tests
```

**Comment by remicollet** [comment]
Please use "Red Hat" (2 words) not "Redhat" ;)

I think you can change RHEL / CentOS / Fedora to ok when 0.2 will be released.

**Comment by troudbal** [comment]
Hi,
Since commit c473be13687ebd98c328f390d936be311dae7db6 the file `config/default.ini` has been renamed to `default.rules` .
The PKGBUILD has to be updated accordingly.

**Comment by jvoisin** [comment]
@troudbal fixed in 210a90e7fe5e45b55031ce1a7d02539ea3185879

**Comment by jvoisin** [comment]
[Cirrus-ci](https://cirrus-ci.org/guide/writing-tasks/) has FreeBSD support, as well as arbitrary docker images; we should give it a try.

**Comment by jvoisin** [comment]
I just got Debian working on [gitlab]( https://gitlab.com/jvoisin/snuffleupagus ). I'll update this issue as I add more images.

**Comment by jvoisin** [comment]
I bumped into some issues when testing with Alpine, I'll investigate. Currently, we have Debian, Ubuntu and Fedora running respectively on their *main* php version.

**Comment by wargio** [comment]
i've uploaded some test debs for debian under the 0.5.1 release

**Comment by estrogently** [comment]
Here's how I got it to build on OpenBSD 6.8:

```sh
doas pkg_add git php autoconf
git clone https://github.com/jvoisin/snuffleupagus
cd snuffleupagus/src
AUTOCONF_VERSION=2.69 phpize-7.4
CPPFLAGS="-I/usr/local/include" ./configure --enable-snuffleupagus --with-php-config=/usr/local/bin/php-config-7.4
```

PHP commands are versioned on OpenBSD, and phpize needs to be passed the installed autoconf version, so adjust the above accordingly based on the PHP and Autoconf versions you actually installed.
Additionally, configure needs to know to look for pcre2.h in /usr/local/include. Aside from that, it's pretty much the standard installation procedure.

**Comment by jvoisin** [comment]
Anything we can do on our end to make OpenBSD users life easier?

**Comment by estrogently** [comment]
> 
> 
> Anything we can do on our end to make OpenBSD users life easier?

If you could get it on PECL then afaik creating OpenBSD packages from there should be relatively easy, since there's already templates & machinery in place to build PECL extensions for every version of PHP they currently provide

**Comment by ccr1969** [comment]
Been trying to compile on windows using vs 2017 but receive this error
C:\php-sdk\php-dev\vc15\x64\php-7.3.26-src\configure.js(6012, 1) Microsoft JScript runtime error: 'PHP_SNUFFLEUPAGUS' is
 undefined

**Comment by jvoisin** [comment]
Yeah, it seems that our [config.w32]( https://github.com/jvoisin/snuffleupagus/blob/master/src/config.w32 ) has never been touched, and never worked in the first place :/

**Comment by ccr1969** [comment]
> 
> 
> Yeah, it seems that our [config.w32](https://github.com/jvoisin/snuffleupagus/blob/master/src/config.w32) has never been touched, and never worked in the first place :/

is this going to be fixed so it can be-compiled by windows or ? is it not worth the time ?

**Comment by jvoisin** [comment]
I'm not going to do it, but contributions are welcome.
