### ISSUE TITLE
[0.4.0] Could not start (invalid configuration)

### ISSUE THREAD

**Issue by remicollet** [jvoisin/snuffleupagus#236]
Test:

```
$ php -n -d extension=modules/snuffleupagus.so -m
$ php -n -d extension=modules/snuffleupagus.so --ri snuffleupagus
Could not startup.
```
With `--no-php-ini`, `sp.configuration_file` is empty, and considered as badly, but `sp.allow_broken_configuration` is true, so PHP cannot startup in this trivial configuration.

**Comment by jvoisin** [comment]
`sp.allow_broken_configuration` is `false` by default:

```
jvoisin@grimhilde 14:09 ~/dev/snuffleupagus php -n -d extension=snuffleupagus.so -d 'sp.allow_broken_configuration=true' --ri snuffleupagus

snuffleupagus

snuffleupagus support => enabled
Version => 0.4.0
Valid config => no

Directive => Local Value => Master Value
sp.configuration_file => no value => no value
sp.allow_broken_configuration => 1 => 1
jvoisin@grimhilde 14:09 ~/dev/snuffleupagus php -n -d extension=snuffleupagus.so --ri snuffleupagus                                                               
Could not startup.
zsh: exit 1     php -n -d extension=snuffleupagus.so --ri snuffleupagus
jvoisin@grimhilde 14:09 ~/dev/snuffleupagus
```

**Comment by remicollet** [comment]
> so you either need to specify a sp.configuration_file or set sp.allow_broken_configuration to true.

Yes, this is exactly the issue I tried to describe: default options break PHP startup.

**Comment by sriccio** [comment]
probably related to https://github.com/nbs-system/snuffleupagus/issues/225#issuecomment-417905225

**Comment by jvoisin** [comment]
@remicollet yes, this is intended. We didn't want to allow people to run PHP with Snuffleupagus and a broken/no configuration.

Is there a better way to prevent people from shooting themselves in the foot?

**Comment by remicollet** [comment]
I agree for **broken** configuration.

But why no configuration should be a issue ?

Ex: for downstream, distribution, we have in `/etc/php.d/40-snuffleupagus.ini`

`sp.configuration_file = '/etc/php.d/snuffleupagus-*.rules'`

 and `/etc/php.d/snuffleupagus-default.rules` which is an empty file.

IMHO **no** configuration, as **empty** configuration, should be considered as valid.

**Comment by jvoisin** [comment]
No configuration means no `sp.configuration_file` and no `sp.allow_broken_configuration`, this is considered as invalid.
Empty configuration means a valid file pointed by `sp.configuration_file`, which is valid, even if the file is empty.
