### ISSUE TITLE
Rethink how we're handling no/invalid configuration

### ISSUE THREAD

**Issue by jvoisin** [jvoisin/snuffleupagus#239]
Currently, we're considering:

- The absence of `sp.configuration_file` and `sp.allow_broken_configuration` as an error.
- A non-existent file pointed by `sp.configuration_file` as an error if `sp.allow_broken_configuration` isn't set
- A existing file but with invalid configuration directive in it pointed by `sp.configuration_file` as an error if `sp.allow_broken_configuration` isn't set

I'm more and more convinced that this isn't the best way™ to handle things. I propose the following:

1. Remove the `sp.allow_broken_configuration` directive
2. Only alert about the (non-)validity of the configuration file in the `phpinfo()`.

This will vastly ease the deployment of Snuffleupagus, give flexibility to people that needs to deploy maybe-borken configurations in production, and break less things.

**Comment by sriccio** [comment]
Hi, I like your proposition.

I might be wrong but it looks to me that it was the case for snuffleupagus <0.3.
A config file that wasn't present displayed "Valid config: No" in phpInfo.

Cheers,
Sébastien

**Comment by wargio** [comment]
I think the way of handle this is: if config file is `""` then:
1. disable the module
2. toss log errors (also on stderr)
3. set phpinfo `Valid config:` to `empty configuration`

if instead the config value is different than `""` then, just handle this as it is done right now.

**Comment by wargio** [comment]
linked to this: https://github.com/jvoisin/snuffleupagus/issues/341
