### ISSUE TITLE
Distribute Snuffleupagus in PECL

### ISSUE THREAD

**Issue by szepeviktor** [jvoisin/snuffleupagus#274]
It would make it more popular and easier to install.

**Comment by jvoisin** [comment]
This will likely be fixed by #275 ♥

**Comment by szepeviktor** [comment]
@jvoisin Could you take it for a ride?

See https://github.com/nbs-system/snuffleupagus/blob/9bb085926a73a84ce6e5f93e7ab08989bf53817f/debian/rules

I am not really into compiling C code and [dh_php](https://manpages.debian.org/stretch/dh-php/dh_php.1.en.html) and the Makefile for PECL: https://salsa.debian.org/php-team/dh-php/blob/master/pkg-pecl.mk

**Comment by jvoisin** [comment]
sure, I'll look at this Monday, Tuesday at worst :)

**Comment by jvoisin** [comment]
Did you test your PR?
It doesn't work here when I'm trying a `make debian`.

Why did you remove all the `cd ./src`? Thinks won't work without it :/

**Comment by jvoisin** [comment]
Any news on this?

**Comment by szepeviktor** [comment]
It is a proposal from my side.

**Comment by jvoisin** [comment]
I gave you [feedback]( https://github.com/nbs-system/snuffleupagus/issues/274#issuecomment-492407417 ) on it, and you didn't reply </3

**Comment by szepeviktor** [comment]
I might not be able to handle a software written in C, although I've contributed a lot to Avature/dh-make-php and I package software for Debian.

**Comment by szepeviktor** [comment]
Then only way for me is to compare snuffleupagus and the redis PECL package - that is something very unprofessional!
