### ISSUE TITLE
cookie_env_var reports environment variable empty

### ISSUE THREAD

**Issue by tdely** [jvoisin/snuffleupagus#283]
Hi,

I've been trying out Snuffleupagus for a bit but I can't seem to make cookie_env_var work. The environment variable is accessible in the script through `$_SERVER['SSL_SESSION_ID']` and `$_ENV['SSL_SESSION_ID']`, but the error log reports: `[error] 16559#16559: *7 FastCGI sent in stderr: "PHP message: PHP Warning:  [snuffleupagus][cookie_encryption] The environment variable 'SSL_SESSION_ID' is empty, cookies are weakly encrypted ..`

If I set `env[SSL_SESSION_ID] = someval` in my PHP-FPM pool configuration the warning goes away, although this assuredly means 'someval' being used by Snuffleupagus instead of the actual SSL session ID.

This same behavior is present when SSL_SESSION_ID is replaced by REMOTE_ADDR.

Does anyone have any idea of what I'm doing wrong?

The software used is:
* Nginx 1.14.2
* PHP-FPM 7.0
* Snuffleupagus commit 73dec8383e517a251ffe1f0c51d65627b281519d.

**Comment by jvoisin** [comment]
This is weird, because we're using [`getenv`]( https://github.com/nbs-system/snuffleupagus/blob/fc742d62f31637f9698cbd46f5ed1aea1847db6d/src/sp_crypt.c#L14 ), and I don't see anything suspicious there.

**Comment by jvoisin** [comment]
Have you tried what's written in [this article]( https://medium.com/@tomahock/passing-system-environment-variables-to-php-fpm-when-using-nginx-a70045370fad ) ?

**Comment by tdely** [comment]
I looked at the article and added to the pool configuration:
```
clear_env = no;
env[SSL_SESSION_ID] = $SSL_SESSION_ID
```
This makes the log quiet, but modifying the `sp_crypt.c`  a bit shows that no actual SSL session ID is being used:
```
if (env_var) {
  PHP_SHA256Update(&ctx, (unsigned char *)env_var, strlen(env_var));
  sp_log_warn("cookie_encryption",
              "The environment variable '%s' "
              "is set, value is '%s'",
              ZSTR_VAL(env_var_zend), env_var);
} else {
  sp_log_warn("cookie_encryption",
              "The environment variable '%s' "
              "is empty, cookies are weakly encrypted",
              ZSTR_VAL(env_var_zend));
}
```
Results in `[snuffleupagus][cookie_encryption] The environment variable 'SSL_SESSION_ID' is set, value is '' in ...`

I'll try it on another installation when I get the time.

**Comment by tdely** [comment]
I've tried a second installation, this time a clean Debian Nginx (the first was compiled to include NAXSI), but the result is the same. Tested by calling session_start() and setting a session variable:

```php
session_start();
$_SESSION['test'] = 'test';
```

I used `cookie_env_var("REMOTE_ADDR")` during this test.

**Comment by jvoisin** [comment]
This is super-duper weird :/
