### ISSUE TITLE
[Debian] PHP config file installation

### ISSUE THREAD

**Issue by Yoda-BZH** [jvoisin/snuffleupagus#291]
Hello,

PHP configuration files should be installed in php directories when the package is installed.

Currenlty, in https://github.com/nbs-system/snuffleupagus/blob/master/debian/rules#L24-L27,
php conf directories are evaluated at package creation time.

This should be in the postinst section.

Thank you !

**Comment by jvoisin** [comment]
Since this is easy to correct, do you want to issue a PR for this?
