### ISSUE TITLE
Chmod "$mode" as octal value

### ISSUE THREAD

**Issue by OldBlacky** [jvoisin/snuffleupagus#317]
I'm running a Nextcloud installation and after installing snuffleupagus i was unable to update to a new version of an app, because the regex for chmod gets triggered. 

It turned out that the default rule of snuffleupagus for chmod values expects them to be an integer value. Nextcloud however uses the value in octal notation, with a leading 0 ([Nextcloud/Config.php#245](https://github.com/nextcloud/server/blob/master/lib/private/Config.php#L245)):
`chmod($this->configFilePath, 0640);`

This leads to a conversion from octal "0640" to dezimal "416" which triggers the regular expression.
`sp.disable_function.function("chmod").param("mode").value_r("^[0-9]{2}[67]$").drop();`

According to the [php documentation](https://www.php.net/manual/en/function.chmod.php) it seems like the octal notation is also the preferred way to go.

Is there a workaround for this problem?

**Comment by jvoisin** [comment]
You can use octal notation in your rules if you want, like `
 sp.disable_function.function("chmod").param("mode").value_r("^0[0-9]{2}7$").drop();`
