### ISSUE TITLE
Something went wrong with a regexp (-28). in Unknown on line 0

### ISSUE THREAD

**Issue by majkeldzordan** [jvoisin/snuffleupagus#321]
Hello,

On PHP Version 7.2.11 value: 
`sp.disable_function.function("ini_set").param("varname").value_r("open_basedir").drop();`
in configuration file generate error 500. Logs:

```
[regexp] Something went wrong with a regexp (-28). in Unknown on line 0
[regexp] Something went wrong with a regexp (-28). in Unknown on line 0
[config] Invalid var name: $varname. in Unknown on line 0
[config] Invalid value 'varname' for `param` on line 1 in Unknown on line 0
[config] Invalid configuration file in Unknown on line 0
```

PHP 7.4 works fine with this rule.

**Comment by jvoisin** [comment]
Weirdly, the return code `-28` [corresponds to the following issue]( https://www.pcre.org/original/doc/html/pcreapi.html ):

>   `PCRE_ERROR_BADMODE        (-28)`
> This error is given if a pattern that was compiled by the 8-bit library is passed to a 16-bit or 32-bit library function, or vice versa. 

This is super-strange, since our regexp-handling code is [pretty straightforward]( https://github.com/jvoisin/snuffleupagus/blob/master/src/sp_pcre_compat.c ) :/
Are you using pcre or pcre2 on PHP7.2?

**Comment by majkeldzordan** [comment]
The same problem on PHP Version 7.0.32. In both cases pcre version is 8.20 2011-10-21.

**Comment by jvoisin** [comment]
A possible explanation might be that you compiled Snuffelupagus using a different version of pcre than the one your PHP deployment is using.

**Comment by majkeldzordan** [comment]
It's the same version of pcre.

**Comment by jvoisin** [comment]
I can't reproduce this locally, nor in the CI, it seems that you'll have to debug it on your own, sorry :/

**Comment by majkeldzordan** [comment]
I have several servers based on the DirectAdmin panel. The same pcre version everywhere - 8.20. It's a shame, because snuffleupagus seems to be a cool option to secure PHP :(

**Comment by jvoisin** [comment]
You can investigate by adding a call to [`pcre2_config`]( http://pcre.org/current/doc/html/pcre2_config.html ) with the `PCRE2_CONFIG_COMPILED_WIDTHS` flag, in `sp_pcre_compat.c` to see what is going on.

**Comment by jvoisin** [comment]
Did you find a solution, @majkeldzordan ?

**Comment by majkeldzordan** [comment]
I just updated pcre and recompiled PHP.
