### ISSUE TITLE
Add possibility to shorten IPs (GDPR compliance)

### ISSUE THREAD

**Issue by DanielRuf** [jvoisin/snuffleupagus#326]
It seems you log full IP addresses at https://github.com/jvoisin/snuffleupagus/commit/b1a4af56f09a9469eeaf006480804451e60fe411

I'm not sure if this logs directly to logfiles or if filter are applied by syslog like it is done at many hosting platforms for accesslog files.

Full IP addresses are not helpful and are GDPR relevant under the jurisdication that an IP address can be connected to a single user.

I already use some WAF which does the part of setting the last part of IPv4 and IPv6 addresses to 0 if the "anonymize IP addresses" option is enabled (which is not the case by default).

So there should be an option to anonamize the last part of an IP address before it is actually logged.

**Comment by jvoisin** [comment]
You might want to ask your lawyer, but there is no need to have this in Snuffleupagus, because of the article [6. 1f]( https://gdpr-info.eu/art-6-gdpr/): 

> Processing shall be lawful only if and to the extent that at least one of the following applies:  […] processing is necessary for the purposes of the legitimate interests pursued by the controller or by a third party, except where such interests are overridden by the interests or fundamental rights and freedoms of the data subject which require protection of personal data, in particular where the data subject is a child.

Snuffleupagus being a security product protecting your legitimate interests, processing PII like IP address is allowed, but it's up to you to have proper log management.

Full IP addresses __are__ helpful, not only to be able to block attackers, but also to identify them and possible report them to your favourite local law enforcement agency.

If you don't want to log the IP addresses, you can set the environment variable `REMOTE_ADDR` to a fixed value.

**Comment by DanielRuf** [comment]
> Full IP addresses **are** helpful, not only to be able to block attackers, but also to identify them and possible report them to your favourite local law enforcement agency

Not really in Germany, as providers are not allowed to store data about it and give you the information that easily.

For blocking the network it is sufficient to have only the part before it as you do not want to block normal ISPs or whole ranges.

> If you don't want to log the IP addresses, you can always set the environment variable `REMOTE_ADDR` to a fixed value.

This is not really a solution. I just need a solution to shorten the IP address like my hosting provider, another WAF solution and others already do it =)

As already written, this should be an optional feature which is disabled by default to allow users to configure / use it if needed. Not everyone needs the full IP address to block attacks (and what does it help to report one single IP address, which is probably just a proxy / VPN, I block the CIDR ranges and networks in such cases if it comes from some hosting provider).

**Comment by DanielRuf** [comment]
> Full IP addresses **are** helpful, not only to be able to block attackers, but also to identify them and possible report them to your favourite local law enforcement agency

Not really in Germany, as providers are not allowed to store data about it that long and do not give you the information that easily.

For blocking the network it is sufficient to have only the part before it as you do not want to block normal ISPs or whole ranges.

> If you don't want to log the IP addresses, you can always set the environment variable `REMOTE_ADDR` to a fixed value.

This is not really a solution. I just need a solution to shorten the IP address like my hosting provider, another WAF solution and others already do it =)

As already written, this should be an optional feature which is disabled by default to allow users to configure / use it if needed. Not everyone needs the full IP address to block attacks (and what does it help to report one single IP address, which is probably just a proxy / VPN, I block the CIDR ranges and networks in such cases if it comes from some hosting provider).

If you think this should not be an option in snuffleupagus I will probably create a fork with this so we can use and test it on some systems and honeypots.

**Comment by jvoisin** [comment]
I discussed with some sysadmin friends of mine, slept on it, and I'm now convinced that it's a feature worth having in Snuffleupagus, thanks for suggesting it!

If you want to implement it yourself, I'll be more than happy to review'n'merge it, otherwise, you'll have to wait a bit for me to have some free time to do it :)

**Comment by DanielRuf** [comment]
Thanks for your feedback and the update. I'll check if I can find some time in the next days, probably not today due to other things at the moment.

**Comment by DanielRuf** [comment]
I guess I have to study some C++, never wrote something in C (only C#) for many years but I could try =)

**Comment by jvoisin** [comment]
Snuffleupagus is written in pure C, and there are already some functions in the codebase to deal with ip addresses and network masks :)

**Comment by DanielRuf** [comment]
I will check that, let's see if I can still write some C code.

**Comment by jvoisin** [comment]
Since nobody implemented this feature, I'm closing this issue for now.
