### ISSUE TITLE
Change debian/control file so we can build debian packages with only php7.4-dev installed

### ISSUE THREAD

**Issue by cypherbits** [jvoisin/snuffleupagus#328]
In the file debian/control change dependencies:
`Build-Depends: debhelper (>= 9), php7.0-dev | php7.1-dev | php7.2-dev`

and set them to:
`Build-Depends: debhelper (>= 9), php7.0-dev | php7.1-dev | php7.2-dev | php7.3-dev | php7.4-dev`
or even just:
`Build-Depends: debhelper (>= 9), php7.2-dev | php7.3-dev | php7.4-dev`
as version 7.0 and 7.1 reached EOL.

**Comment by jvoisin** [comment]
Done in 4a5a1922f105bf0d4ee002088a6e6ece67ae0b9e, thanks for the headsup
