### ISSUE TITLE
[Feature] How to check from PHP if we enabled a non-cookie encryption

### ISSUE THREAD

**Issue by cypherbits** [jvoisin/snuffleupagus#331]
Hello, it presents to me the following use-case:
- Enabling non-session cookie encryption to encrypt a cookie sent to the user browser is done with 
snuffleupagus config file.

- I want to check not only if snuffleupagus extension is enabled but if the cookie encryption is enabled for say the cookie "confidential" so I can encrypt it manually in PHP or not.

I propose a function for checking if a cookie encryption is enabled passing by parameter the name of the cookie.

**Comment by jvoisin** [comment]
You can enable the simulation mode: Snuffleupagus won't drop non-encrypted cookies, but will encrypt all new ones. I'm not sure we want to expose Snuffleupagus to php code :/

**Comment by cypherbits** [comment]
Well, my need is to check if a cookie was encrypted automatically by Snuffleupagus or not so in case it is not encrypted I do it...

**Comment by jvoisin** [comment]
If you use Snuffleupagus in simulation mode, this is exactly what will happen :)

**Comment by cypherbits** [comment]
@jvoisin sorry, but I'm not following you... if you enable simulation mode it only writes to log, right? and allows not encrypted cookies to be sent by the client.
I don't talk about old unencrypted cookies and new encrypted cookies. I'm talking about a way to check if the encryption is enabled for a cookie named "something" so I can take actions on the PHP code like manual encryption. 
This is for shared hostings that cannot install Snuffleupagus extensions but want to enable cookie encryption. I need to know if our cookie encryption is enabled for "something". A way to check if 
`sp.cookie.name("something").encrypt();`
is enabled.

**Comment by jvoisin** [comment]
This is exactly what the simulation mode [is doing]( https://github.com/jvoisin/snuffleupagus/blob/master/src/sp_crypt.c#L51-L57 ) :)

**Comment by cypherbits** [comment]
Sorry... but no...
What I see there is that if you set the simulation mode, the non-encrypted cookies are kept, ok. But I'm not saying that. What I want is to know from PHP side if a cookie was encrypted or not. If cookie encryption is enabled for a cookie or not.

Like:

```
if (snuf_cookie_encrypted('cookie_name')){
//ok, encryption is enabled, so we do nothing as Snuffleupagus do it for us in a transparent way.
}else{
//Encrypt or decrypt it manually using libsodium and our secret key.
}
```

**Comment by jvoisin** [comment]
Why do you want to manually encrypt the cookie?
Snuffleupagus in simulation mode will:
- accept non-encrypted cookies
- encrypt new cookies

**Comment by cypherbits** [comment]
> Why do you want to manually encrypt the cookie?
> Snuffleupagus in simulation mode will:
> 
>     * accept non-encrypted cookies
> 
>     * encrypt new cookies

I want to manually encrypt the cookie if Snuffleupagus is not installed on a shared hosting OR if the admin did not enable cookie encryption... but right now I don't have a way to check if a cookie encryption was enabled or not.

**Comment by jvoisin** [comment]
Sessions cookies are encrypted server-side, but I guess you could re-implement the *regular* cookies encryption in pure php: since Snuffleupagus is using authenticated encryption, you can check if the cookies are encrypted by trying to decrypt them: if it works, they are encrypted.

**Comment by cypherbits** [comment]
> Sessions cookies are encrypted server-side, but I guess you could re-implement the _regular_ cookies encryption in pure php: since Snuffleupagus is using authenticated encryption, you can check if the cookies are encrypted by trying to decrypt them: if it works, they are encrypted.

But, I'm talking about regular cookies... the cookie data sent to the client is encrypted with
`sp.cookie.name("something").encrypt();`
right?

**Comment by jvoisin** [comment]
I think so, yes

**Comment by cypherbits** [comment]
Hi, anything new on this? Do you finally understand what I mean?

**Comment by kpcyrd** [comment]
@cypherbits if you already have a system in place to encrypt cookies, why not migrate that to a php-reimplementation of what snuffleupagus uses to encrypt the cookie?

The relevant functions are:
https://github.com/jvoisin/snuffleupagus/blob/1b52614c06b60ced6caecd8dcaa0911ed3aa72e2/src/sp_crypt.c#L3-L38
https://github.com/jvoisin/snuffleupagus/blob/1b52614c06b60ced6caecd8dcaa0911ed3aa72e2/src/sp_crypt.c#L93-L97

The function `crypto_secretbox_open` is available in recent versions of php as [`sodium_crypto_secretbox_open`](https://www.php.net/manual/en/function.sodium-crypto-secretbox-open.php).

**Comment by jvoisin** [comment]
I'm not sure I understand what you're trying to do:

- If snuffleupagus is installed, just use the simulation mode
- If snuffleupagus isn't installed, you can either implement the cookie decryption in pure PHP, but it seems easier to simply drop the cookie, and set a new one.

**Comment by cypherbits** [comment]
Hi @jvoisin , please read the previous comments to see if reading again you understand. I think I explained good already... 

The goal is to always encrypt cookies even if 
1) snuf is not installed 
2) snuf is installed but cookie encryption for cookie name "mysecretcookie" is not enabled.

The question is: how I check from PHP code case 2? I don't want to double encrypt it.

**Comment by kpcyrd** [comment]
If I got it right it's for a codebase that's published on eg. github and a user may or may not have snuffleupagus installed, so the developer doesn't control the environment it's deployed into.

**Comment by cypherbits** [comment]
> If I got it right it's for a codebase that's published on eg. github and a user may or may not have snuffleupagus installed, so the developer doesn't control the environment it's deployed into.

Yes, you got it right.

If I make an open source app that can be installed on a shared hosting with no snuf installed, we can encrypt it writting php code. But if you can install snuf and configure cookie encryption, how can we check if its installed to not double encrypt the cookie in php??

**Comment by cypherbits** [comment]
@jvoisin this is what I want to be available from PHP:

![imagen](https://user-images.githubusercontent.com/10424900/86280288-ca086080-bbdb-11ea-8483-fb2f97b43e8d.png)

A way to check if cookie name "some_cookie" was configured to be encrypted.

**Comment by jvoisin** [comment]
The only way would be to reimplement the crypto I'm afraid :/

**Comment by cypherbits** [comment]
@jvoisin I don't see why. It's just a function to check if a cookie was configured to be encrypted on the snuf config...

**Comment by jvoisin** [comment]
Checking the configuration would tell you that cookies are currently being encrypted, not that a particular cookie from a request is encrypted.

**Comment by cypherbits** [comment]
> Checking the configuration would tell you that cookies are currently being encrypted, not that a particular cookie from a request is encrypted.

That is what I want...

**Comment by jvoisin** [comment]
Then you can simply grep snuffleupagus' configuration for the directive you're looking for?

**Comment by cypherbits** [comment]
> Then you can simply grep snuffleupagus' configuration for the directive you're looking for?

Can anyone grep that config file from PHP code ? ......

**Comment by jvoisin** [comment]
Nothing prevents you from making it accessible the the PHP process, although this might lower your security level.

**Comment by cypherbits** [comment]
And that is why I opened this issue, to not make it weaker... I only want a function to check if a cookie is configured to be encrypted or not so I can encrypt it myself or not on PHP side...

**Comment by jvoisin** [comment]
There is none then :/

**Comment by cypherbits** [comment]
I don't know if you are kidding me or what... 

I need a function accessible in PHP code that checks if a cookie was defined in the Snuffleupagus config as to be encrypted. 

Just that simple.

**Comment by jvoisin** [comment]
Such a function won't be implemented, for a couple of reasons:

- Your usecase is super-duper-specific. So specific that I genuinely don't understand it.
- This can be ~done by using the *simulation* mode, which will silently encrypt unencrypted cookies
- Exposing part of snuffleupagus' configuration will weaker (a tiny bit) its security
- You can do it yourself by parsing Snuffleupagus' configuration

**Comment by wargio** [comment]
> If my PHP application is installed on a shared hosting where Snuffleupagus is not installed and configured to encrypt a cookie, I can do it in PHP, but how to detect if the cookie is already encrypted with Snuffleupagus or not??

if you are double encrypting the cookie, unless the double encryption is RSA or similar (which weakens the ciphertext security), you should not care about this; since `crypto_secretbox` uses `crypto_secretbox_xsalsa20poly1305` (and i think there is some work to have also AES in GCM mode) this can't be a problem since the stream cipher used doesn't have such math issue on the given input.

From your description seems that either way, you are trying to do an web application scan or MITM for some particular reasons.
Can you explain exactly what is the usecase of this? because you said you do not control the website which may run or not SP.

You can always read the cookie and check the entropy of N cookies.

**Comment by cypherbits** [comment]
@wargio 
I think I'm gonna cry. Maybe it's my fault and I didn't explain it well, but I don't want to double encrypt anything, just make sure it is encrypted.

I want my PHP application cookie to be encrypted, even if there is not Snuffleupagus or even if there is Snuffleupagus installed but not configured to encrypt my cookie. The goal is to be always encrypted. 

1- If there is not Snuffleupagus we encrypt the cookie in PHP code.
2- If there is Snuffleupagus installed BUT cookie encryption is not enabled, we encrypt it with PHP code.
3- If there is Snuffleupagus installed AND cookie encryption is enabled, we do NOT encrypt with PHP code.

The question is: how can I check case 2? 

The answer is a public PHP function that returns if `sp.cookie.name("something").encrypt();` is set or not.

**Comment by jvoisin** [comment]
Nobody showed up to work on this issue, and I don't plan to, so closing this one for now.
