### ISSUE TITLE
Build tests fail on Ubuntu 20.04, PHP 7.4.5

### ISSUE THREAD

**Issue by DavidOsipov** [jvoisin/snuffleupagus#333]
Hello and thank your for your effort to secure PHP! _I'm not an IT specialist, system administration is just my hobby._

**Issue:** Run make test - tests fail.

**Test result summary**:
[Test results.txt](https://github.com/jvoisin/snuffleupagus/files/4598018/Test.results.txt)

**System info:** 
Ubuntu 20.04 with latest packages and updates, kernel 5.4.0-29-generic, arch. x86_64.
pcre library 8.43 + pcre-dev
Openssl 1.1.1g
PHP 7.4.5
[config.log](https://github.com/jvoisin/snuffleupagus/files/4597989/config.log)

If there is something needed, just let me know.

**Comment by jvoisin** [comment]
Can you try to run a `make debug` instead?

**Comment by DavidOsipov** [comment]
> Can you try to run a `make debug` instead?

Done for `make` and make `test`.

[snuffleupagus.debug.txt](https://github.com/jvoisin/snuffleupagus/files/4603997/snuffleupagus.debug.txt)
[snuffleupagus_tests.debug.txt](https://github.com/jvoisin/snuffleupagus/files/4603998/snuffleupagus_tests.debug.txt)

**Comment by jvoisin** [comment]
Do you have `php-curl` and `php-xml` installed?

**Comment by DavidOsipov** [comment]
Yes, everything is installed

**Comment by DavidOsipov** [comment]
Maybe you require anything else on this matter?

**Comment by jvoisin** [comment]
No, I only need to find some free time to investigate this issue :)

**Comment by jvoisin** [comment]
It should™ be fixed on the current master, can you try?

**Comment by DavidOsipov** [comment]
Tried but the same 13 tests failed :( Different logs were collected on different stages of installation.
[debug.txt](https://github.com/jvoisin/snuffleupagus/files/4630659/debug.txt)
[debug1.txt](https://github.com/jvoisin/snuffleupagus/files/4630660/debug1.txt)
[debug2.txt](https://github.com/jvoisin/snuffleupagus/files/4630661/debug2.txt)
[debug3.txt](https://github.com/jvoisin/snuffleupagus/files/4630662/debug3.txt)

**Comment by jvoisin** [comment]
Can you please share the content of the `*.out` files corresponding to the failing tests? They should be laying around next to them.

**Comment by DavidOsipov** [comment]
Here you go, copied every `.out` file in the directory.
[Files.zip](https://github.com/jvoisin/snuffleupagus/files/4751131/Files.zip)

**Comment by jvoisin** [comment]
Thanks!

I looks like PHP doesn't enable the `curl` and `xml` extensions in the testsuite, no idea why :/

**Comment by DavidOsipov** [comment]
![curl](https://user-images.githubusercontent.com/38164582/85125840-011e5f80-b235-11ea-9e9b-6e88c9ee6b97.JPG)
![xml](https://user-images.githubusercontent.com/38164582/85125842-02e82300-b235-11ea-9445-f98f040e0c69.JPG)

Very strange :( I've rechecked everything, these 2 modules are enabled. Weird, might be a bug in a php? If you have any suggestion very to search for a problem on my server, just tell me :)

**Comment by jvoisin** [comment]
Maybe it's enabled in your `php-fpm`, but not in your cli?

**Comment by DavidOsipov** [comment]
Nope. I have configured yet another server at AWS and installed Ubuntu 20.04, the same error. These two modules are enable as well, used `php -m` to find out.
[php_modules.txt](https://github.com/jvoisin/snuffleupagus/files/4806605/php_modules.txt)

The only common thing between my two servers is that [I'm using this PPA](https://launchpad.net/~ondrej)

**Comment by donbowman** [comment]
This Dockerfile will repro:

```
FROM ubuntu:20.04 as snuffleupagus
RUN apt-get update \
 && echo Etc/UTC > /etc/timezone \
 && ln -snf /usr/share/zoneinfo/UTC /etc/localtime \
 && apt-get install -y build-essential git dh-php php-curl libpcre3-dev libcgi-fast-perl php7.4-dev \
    php7.4-cgi \
    php7.4-cli \
    php7.4-curl \
    php7.4-fpm \
    php7.4-gd \
    php7.4-xml \
    php7.4-xmlrpc \
    php-xml \
    php-curl \
 && git clone https://github.com/jvoisin/snuffleupagus /src/snuffleupagus \
 && cd /src/snuffleupagus \
 && make debian
```

**Comment by wargio** [comment]
@donbowman does it fail due the tests?

if yes, try this:
```
diff --git a/debian/rules b/debian/rules
index 70965bb..bd9077c 100755
--- a/debian/rules
+++ b/debian/rules
@@ -28,4 +28,4 @@ override_dh_auto_install:

 override_dh_auto_test:
   sed -i "s/\\\$\$ext_params -d display_errors=0 -r/-d display_errors=0 -r/" src/run-tests.php
-  TEST_PHP_ARGS="-q" REPORT_EXIST_STATUS=1 make -C src test
+  echo "skip tests"
```

**Comment by donbowman** [comment]
yes same error as origin of this thread in a test. It passes when run on my 20.04 desktop, but fails when run in the container.
```
FAILED TEST SUMMARY
---------------------------------------------------------------------
Readonly execution attempt (simulation mode) [tests/deny_writable/deny_writable_execution_simulation.phpt]
=====================================================================
```

so sure, disabling the tests it will build. But, does the failed test not indicate an issue?

**Comment by wargio** [comment]
> yes same error as origin of this thread in a test. It passes when run on my 20.04 desktop, but fails when run in the container.
> 
> ```
> FAILED TEST SUMMARY
> ---------------------------------------------------------------------
> Readonly execution attempt (simulation mode) [tests/deny_writable/deny_writable_execution_simulation.phpt]
> =====================================================================
> ```
> 
> so sure, disabling the tests it will build. But, does the failed test not indicate an issue?

depends which version are you using. the current release has some broken tests for other reasons.

**Comment by donbowman** [comment]
v0.5.1 fails this way as does -master.

**Comment by jvoisin** [comment]
For the failing `Readonly execution attempt (simulation mode)`, it's likely because you're running the testsuite as root.

**Comment by jvoisin** [comment]
The tests are passing on Ubuntu 20.10 (groovy), on php 7.4.9.
