### ISSUE TITLE
disable_function dump fails

### ISSUE THREAD

**Issue by TaAL7** [jvoisin/snuffleupagus#335]
i get:
```
[07-Jun-2020 20:14:59 UTC] PHP Fatal error:  [snuffleupagus][config] Invalid configuration file in Unknown on line 0
```

if i use:

```python
sp.disable_function.function("mysql_query").ret("FALSE").dump("/some/folder/log");
```

log is a folder and the line in the config file where this is placed is not 0.

**Comment by jvoisin** [comment]
Because you need to add an action, like `drop` or `allow`:

```
 sp.disable_function.function("mysql_query").ret("FALSE").dump("/some/folder/log").allow();
```

**Comment by TaAL7** [comment]
Oh okay, the docs (https://snuffleupagus.readthedocs.io/config.html#actions) make them look like equals. Probably a good idea to state clearly that dump() still needs an allow() or deny() afterwards.
Sorry for the false alarm.

**Comment by jvoisin** [comment]
You're absolutely right, done in 7f9602ebc23582195d63eb35f1de1961297f2e00, thanks!
