### ISSUE TITLE
About compatibility of Heroku

### ISSUE THREAD

**Issue by kulisu** [jvoisin/snuffleupagus#336]
Hi and thank for amazing project to harden PHP applications.
I try to deploy SP on Heroku (PHP7.4, [heroku-18](https://devcenter.heroku.com/articles/php-support#supported-versions)) to get better protection.

I noticed this will crash application when `sp.log_media("php")` is specified.
It's working good and smooth when I specified `sp.log_media("syslog")` instead.

But I can't get SP log in this mode, so I try to dig the code and figure it out.
Finally [zend_error](https://github.com/jvoisin/snuffleupagus/blob/master/src/sp_utils.c#L37) function seems to break the Heroku deployment I guessed.

```
2020-07-02T12:21:52.465450+00:00 app[api]: Release v119 created by user chris@example.com
2020-07-02T12:21:53.889399+00:00 heroku[web.1]: Starting process with command `vendor/bin/heroku-php-apache2 -F config/.php.ini public/`
2020-07-02T12:21:54.075582+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-07-02T12:21:54.125333+00:00 app[web.1]: Stopping httpd...
2020-07-02T12:21:54.126635+00:00 app[web.1]: SIGTERM received, attempting graceful shutdown...
2020-07-02T12:21:54.127999+00:00 app[web.1]: Stopping php-fpm...
2020-07-02T12:21:54.135028+00:00 app[web.1]: Shutdown complete.
2020-07-02T12:21:54.219333+00:00 heroku[web.1]: Process exited with status 143
2020-07-02T12:21:56.571026+00:00 app[web.1]: [heroku-exec] Starting
2020-07-02T12:21:57.362702+00:00 app[web.1]: Unable to determine Composer vendor-dir setting; is 'composer' executable on path or 'composer.phar' in current working directory?
2020-07-02T12:21:57.429628+00:00 heroku[web.1]: Process exited with status 1
2020-07-02T12:21:57.470123+00:00 heroku[web.1]: State changed from starting to crashed
```

```
2020-07-02T12:23:29.182229+00:00 app[api]: Release v120 created by user chris@example.com
2020-07-02T12:23:29.000000+00:00 app[api]: Build succeeded
2020-07-02T12:23:30.807877+00:00 heroku[web.1]: Starting process with command `vendor/bin/heroku-php-apache2 -F config/.php.ini public/`
2020-07-02T12:23:33.283824+00:00 app[web.1]: [heroku-exec] Starting
2020-07-02T12:23:34.225526+00:00 app[web.1]: DOCUMENT_ROOT changed to 'public/'
2020-07-02T12:23:34.225620+00:00 app[web.1]: Using PHP-FPM configuration include 'config/.php.ini'
2020-07-02T12:23:34.319130+00:00 app[web.1]: Detected 536870912 Bytes of RAM
2020-07-02T12:23:34.366133+00:00 app[web.1]: PHP memory_limit is 128M Bytes
2020-07-02T12:23:34.379623+00:00 app[web.1]: Starting php-fpm with 4 workers...
2020-07-02T12:23:34.487367+00:00 app[web.1]: Starting httpd...
2020-07-02T12:23:35.138709+00:00 heroku[web.1]: State changed from starting to up
```

### Dirty Patch
[sp_utils.txt](https://github.com/jvoisin/snuffleupagus/files/4864823/sp_utils.txt)

I decide to output SP log to `stderr`, blocking and logging both work !
Is there any settings I messed up ? thanks. 

Remind: above patch is a workaround and SHOULD NOT deploy to production.

```
<snipped>
2020-07-02T14:17:32.985713+00:00 app[web.1]: Starting php-fpm with 4 workers...
2020-07-02T14:17:33.084648+00:00 app[web.1]: Starting httpd...
2020-07-02T14:17:33.578194+00:00 heroku[web.1]: State changed from starting to up
2020-07-02T14:17:38.477751+00:00 heroku[router]: at=info method=GET path="/test2.php?cmd=id|try_to_injection_here" host=example.herokuapp.com request_id=1 fwd="1.2.3.4" dyno=web.1 connect=1ms service=3ms status=200 bytes=150 protocol=https
2020-07-02T14:17:38.477621+00:00 app[web.1]: [snuffleupagus][unknown][disabled_function] Aborted execution on call of the function 'exec', because its argument '$command' content (id|try_to_injection_here) matched a rule in /app/public/test2.php on line 1
2020-07-02T14:17:38.478128+00:00 app[web.1]: 10.45.9.232 - - [02/Jul/2020:14:17:38 +0000] "GET /test2.php?cmd=id|try_to_injection_here HTTP/1.1" 200 - "-" "curl/7.68.0"
```

### Known Issues

- REMOTE_ADDR and HTTP_X_FORWARDED_FOR are not available in `getenv`

### Heroku Environment

- Apache: 2.4.43
- PHP: 7.4.7
- Ubuntu 18.04.4 LTS

### Reproduce Pack

[test-sp-logging.zip](https://github.com/jvoisin/snuffleupagus/files/4865062/test-sp-logging.zip)

1. Decompress above zip and deploy it to Heroku (with [PHP7.4 pack](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-php))
2. Log will display that app is crashed by running `heroku logs --tail`
3. Uncomment `scripts/install_php_ext-snuffleupagus.sh` L#17 and L#18
4. Deploy it again and access `http://app_url/test2.php?cmd=id|try_to_injection_here` 
5. Log should display _[snuffleupagus][unknown][disabled_function] Aborted execution on .._

```
wget https://github.com/jvoisin/snuffleupagus/files/4865062/test-sp-logging.zip -O /tmp/test-sp-logging.zip
unzip /tmp/test-sp-logging.zip -d /tmp

cd /tmp/test-sp-logging

git init
/usr/local/bin/heroku git:remote -a <YOURHEROKU_APP_NAME>
git add .; git commit -am "test"; git push heroku master

/usr/local/bin/heroku logs --tail
```

**Comment by kulisu** [comment]
Hi again,

Below default rules seem to break Heroku [bootstrap script](https://github.com/heroku/heroku-buildpack-php/blob/master/bin/heroku-php-apache2#L309).

```
# Since it's now burned, me might as well mitigate it publicly
sp.disable_function.function("putenv").param("setting").value_r("LD_").drop();

# Prevent various `include`-related vulnerabilities
sp.disable_function.function("require").value_r("\.(inc|phtml|php)$").allow();
sp.disable_function.function("require").drop()

# Prevent `system`-related injections
sp.disable_function.function("exec").param("command").value_r("[$|;&`\\n\\(\\)\\\\]").drop();

# Prevent runtime modification of interesting things
sp.disable_function.function("ini_set").param("varname").value("memory_limit").drop();

# Detect some backdoors via environnement recon
sp.disable_function.function("ini_get").param("varname").value("open_basedir").drop();
sp.disable_function.function("function_exists").param("function_name").value("exec").drop();
sp.disable_function.function("function_exists").param("function_name").value("proc_open").drop();

# Logging lockdown
sp.disable_function.function("ini_set").param("varname").value_r("display_errors").drop()
```

**Comment by jvoisin** [comment]
Thanks you very much for the detailed bug report!

I've refactored and improved a bit how snuffleupagus does its logging, which might or might not resolve your issue.

I'll try to create an account on heroku this Sunday to diagnose what's going on :)

**Comment by jvoisin** [comment]
I followed your instructions line by line, Snuffleupagus is [enabled]( https://snuffleupagus-test.herokuapp.com/test1.php ), but it seems that it's [not blocking anything]( https://snuffleupagus-test.herokuapp.com/test2.php?cmd=;;;;;;;; ). I'll investigate more

**Comment by kulisu** [comment]
Hello !

Thanks for quick reply ! After digging Heroku [bootstrap](https://github.com/heroku/heroku-buildpack-php/blob/master/bin/heroku-php-apache2#L309) script ..
It seems that something goes wrong while executing `composer`.

Reference to #225 #260 issues, I decide to load an empty configuration first.
This will ensure all Heroku CLI scripts are working as expected without any restrictions.

```
; /app/.heroku/php/etc/php/conf.d/999-ext-snuffleupagus.ini
extension=snuffleupagus.so
sp.allow_broken_configuration=on
sp.configuration_file=/dev/null
```

**Then put [default rules](https://github.com/jvoisin/snuffleupagus/blob/master/config/default.rules#L72) back by setting `php_admin_value` in PHP-FPM configuration.**
And it works like a charm ! both FPM workers and web server are working now :))))))))))

```
; /app/config/.php.ini
php_admin_flag[sp.allow_broken_configuration] = off
php_admin_value[sp.configuration_file]        = /app/config/.snuffleupagus_default.ini
```

I also created a [skeleton project](https://github.com/jvoisin/snuffleupagus/files/4873682/heroku-x-snuffleupagus.zip) for quick hardening Heroku App by Snuffleupagus.
Hope this can help someone, please feel free to let me know if you have further questions !

```
# Deployment

wget https://github.com/jvoisin/snuffleupagus/files/4873682/heroku-x-snuffleupagus.zip -O /tmp/heroku-x-snuffleupagus.zip
unzip /tmp/heroku-x-snuffleupagus.zip -d /tmp

cd /tmp/heroku-x-snuffleupagus

git init
heroku git:remote -a <YOUR_HEROKU_APP_NAME_HERE>

git add . && git commit -am "make it better" && git push heroku master
/usr/local/bin/heroku logs --tail
```

```
# Testing (this website may not alive too long)
# https://heroku-x-snuffleupagus.herokuapp.com/

2020-07-04T19:01:30.255910+00:00 heroku[router]: at=info method=GET path="/test2.php?cmd=ls%20-alh%20/tmp" host=heroku-x-snuffleupagus.herokuapp.com request_id=1 fwd="1.2.3.4" dyno=web.1 connect=1ms service=13ms status=200 bytes=337 protocol=https
2020-07-04T19:01:30.253742+00:00 app[web.1]: 10.99.209.116 - - [04/Jul/2020:19:01:30 +0000] "GET /test2.php?cmd=ls%20-alh%20/tmp HTTP/1.1" 200 48 "-" "curl/7.68.0

2020-07-04T19:01:34.702905+00:00 heroku[router]: at=info method=GET path="/test2.php?cmd=ls%20-alh%20/tmp;id" host=heroku-x-snuffleupagus.herokuapp.com request_id=b22 fwd="1.2.3.4" dyno=web.1 connect=1ms service=2ms status=500 bytes=288 protocol=https
2020-07-04T19:01:34.704486+00:00 app[web.1]: [04-Jul-2020 19:01:34 UTC] PHP Fatal error:  [snuffleupagus][0.0.0.0][disabled_function] Aborted execution on call of the function 'exec', because its argument '$command' content (ls -alh /tmp;id) matched a rule in /app/public/test2.php on line 1

```

**Comment by jvoisin** [comment]
Would you mind submitting a pull request to the [documentation]( https://github.com/jvoisin/snuffleupagus/tree/master/doc/source) to explain the whole process of deploying a snuffleupagus-powered php stack on heroku?

Otherwise, I'll try to do you, and ask you for a small review if you don't mind.

**Comment by kulisu** [comment]
`REMOTE_ADDR` and `HTTP_X_FORWARDED_FOR` are not available in [getenv](https://github.com/jvoisin/snuffleupagus/blob/b849f33ba6dbfe040927b920846742d517a67bce/src/sp_utils.c#L12).
Maybe we can extract these values and combine then from [TRACK_VARS_SERVER](https://github.com/jvoisin/snuffleupagus/blob/b849f33ba6dbfe040927b920846742d517a67bce/src/sp_utils.c#L116) ?

**Comment by jvoisin** [comment]
Isn't `TRACK_VARS_SERVER` filled with environment variables?

**Comment by kulisu** [comment]
`TRACK_VARS_SERVER` is filled, but snuffleupagus can not display correct IP
I have no idea why `getenv` can not extract REMOTE_ADDR in Heroku PHP-FPM

### snuffleupagus log

heroku[router]: at=info method=GET path="/test_snuffleupagus.php?cmd=echo%20 \`whoami\`" host=example.herokuapp.com request_id=5678 fwd="1.2.3.4" dyno=web.1 connect=1ms service=2ms status=500 bytes=288 protocol=https

app[web.1]: PHP Fatal error:  [snuffleupagus]`[0.0.0.0]`[Eval_whitelist] The function 'echo' isn't in the eval whitelist, dropping its call. in /app/public/test_snuffleupagus.php(2) : eval()'d code on line 1

### snuffleupagus dump

RULE: sp.eval_whitelist.list("whatever").dump("/tmp/snuffleupagus/");
FILE: /app/public/test_snuffleupagus.php:2

GET:cmd='echo \`whoami\`'
POST:

COOKIE:
SERVER:DYNO='web.1' PWD='/app' HOME='/app' PORT='16761' DOCUMENT_ROOT='/app/public' WEB_CONCURRENCY='4' SHLVL='2' _='/app/.heroku/php/sbin/php-fpm' USER='u12345' SCRIPT_NAME='/test_snuffleupagus.php' REQUEST_URI='/test_snuffleupagus.php?cmd=echo%20whoami' QUERY_STRING='cmd=echo%20 \`whoami\`' REQUEST_METHOD='GET' SERVER_PROTOCOL='HTTP/1.1' GATEWAY_INTERFACE='CGI/1.1' REMOTE_PORT='32634' SCRIPT_FILENAME='/app/public/test_snuffleupagus.php' SERVER_ADMIN='you@example.com' CONTEXT_DOCUMENT_ROOT='/app/public' CONTEXT_PREFIX='' REQUEST_SCHEME='http' REMOTE_ADDR='10.31.72.133' SERVER_PORT='80' SERVER_ADDR='172.18.171.186' SERVER_NAME='example.herokuapp.com' SERVER_SOFTWARE='Apache' SERVER_SIGNATURE='' HTTP_VIA='1.1 vegur' HTTP_X_FORWARDED_PORT='443' HTTP_X_FORWARDED_PROTO='https' `HTTP_X_FORWARDED_FOR='1.2.3.4'` HTTP_USER_AGENT='curl/7.68.0' HTTP_HOST='example.herokuapp.com' FCGI_ROLE='RESPONDER' PHP_SELF='/test_snuffleupagus.php' <.. SNIPPED>

**Comment by jvoisin** [comment]
Can you try to run the `env` command to see what's available?

**Comment by kulisu** [comment]
It seems that Apache environment are disappeared.
I can only get few variables by running `env` command in PHP script.

```
<?php
    # https://example.herokuapp.com/test.php?cmd=env

    exec($_REQUEST['cmd'], $output);
    var_dump($output);
?>
```

```
array(9) {
  [0]=>
  string(10) "DYNO=web.1"
  [1]=>
  string(15) "PWD=/app/public"
  [2]=>
  string(9) "HOME=/app"
  [3]=>
  string(10) "PORT=35368"
  [4]=>
  string(25) "DOCUMENT_ROOT=/app/public"
  [5]=>
  string(17) "WEB_CONCURRENCY=4"
  [6]=>
  string(7) "SHLVL=2"
  [7]=>
  string(31) "_=/app/.heroku/php/sbin/php-fpm"
  [8]=>
  string(11) "USER=u12345"
}
```

**Comment by kulisu** [comment]
I also build an app for quick testing.
http://heroku-x-snuffleupagus.herokuapp.com/

**Comment by jvoisin** [comment]
[Apparently]( https://github.com/iphoting/heroku-buildpack-php-tyler/blob/master/conf/php-fpm.conf#L4630), you need to manually specify which variables you want to export

**Comment by jvoisin** [comment]
Can you confirm that it's working?

**Comment by kulisu** [comment]
I can set any variables in Apache / PHP-FPM configuration (eg, [TESTTEST666](http://heroku-x-snuffleupagus.herokuapp.com/phpinfo.php) in phpinfo()).
But I don't know how to pass `$_SERVER['REMOTE_ADDR']` to [env[REMOTE_ADDR]](https://github.com/iphoting/heroku-buildpack-php-tyler/blob/master/conf/php-fpm.conf#L468) in PHP-FPM.

**Comment by jvoisin** [comment]
Try `env[REMOTE_ADDR] = $REMOTE_ADDR`, it should may work™

**Comment by kulisu** [comment]
ummmmm, no luck here (both Apache / PHP-FPM tried)

https://heroku-x-snuffleupagus.herokuapp.com/phpinfo.php
http://heroku-x-snuffleupagus.herokuapp.com/exec.php?cmd=env

```
; PHP-FPM configuration to test

php_admin_value[variables_order] = GPCSE

; clear_env  = no
; access.log = /tmp/test-by-chris.log
env[TESTTEST666] = "this is a test by Chris"
env[TESTTEST888] = $TESTTEST777
env[REMOTE_ADDR] = $REMOTE_ADDR
```

```
# Apache configuration to test

SetEnv REMOTE_ADDR $REMOTE_ADDR

<Directory "${HEROKU_APP_DIR}/public">
    AllowOverride None
    Options -FollowSymLinks +Indexes -MultiViews
</Directory>
```

**Comment by jvoisin** [comment]
I pushed 05c98eb39f07bd951b6047e154db6479828e2a11 which should fix the issue :)

**Comment by jvoisin** [comment]
Can you confirm that the fix is working (or not), so that we can close this issue?

**Comment by kulisu** [comment]
sorry for delayed reply.
the fix ([here](https://github.com/jvoisin/snuffleupagus/commit/05c98eb39f07bd951b6047e154db6479828e2a11)) is not working :( 

https://heroku-x-snuffleupagus.herokuapp.com/phpinfo.php
https://heroku-x-snuffleupagus.herokuapp.com/test/exec.php?cmd=id

### Deploy

```
root@kali:/tmp/heroku-x-snuffleupagus# !git
git add . && git commit -am "make it better" && git push heroku master
[master 7b4a25c] make it better
 1 file changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 build/extensions/snuffleupagus/compiled/20190902/snuffleupagus.so
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (5/5), 432 bytes | 432.00 KiB/s, done.
Total 5 (delta 1), reused 3 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> PHP app detected
remote: -----> Bootstrapping...
remote: -----> Installing platform packages...
remote:        - php (7.4.8)
remote:        - apache (2.4.43)
remote:        - nginx (1.18.0)
remote: -----> Installing dependencies...
remote:        Composer version 1.10.7 2020-06-03 10:03:56
remote:        Loading composer repositories with package information
remote:        Installing dependencies from lock file
remote:        Nothing to install or update
remote:        Generating optimized autoload files
remote: -----> Running 'composer compile'...
remote:        > bash build/scripts/install_php_ext-snuffleupagus.sh
remote:        - Start running installation
remote:          - Checking current PHP version
remote:            * No pre-compiled module found
remote:          - Downloading extension ..
remote:          - Configuring extension ..
remote:          - Compiling extension ..
remote:          - Installing extension ..
remote:          - Writing default (dummy) settings
remote:            * It's enabled with empty configuration to avoid conflicting Heroku CLI scripts.
remote:            * Specify `php_admin_value[sp.configuration]` in PHP-FPM to protect web application.
remote:            * https://devcenter.heroku.com/articles/custom-php-settings#php-fpm-configuration-include
remote:        - Succeed to install extension
remote:        > bash build/scripts/harden_php_application.sh
remote:        - Start hardening application
remote:          - Setting all PHP scripts to read-only
remote:          - Setting all web files to read-only
remote:          - Setting all web folders to read-only
remote:        - Succeed to harden application
remote:        > find ./build -type f -exec shred -f -u -z {} \; && rm -rf ./build
remote: -----> Preparing runtime environment...
remote: -----> Checking for additional extensions to install...
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing...
remote:        Done: 14.5M
remote: -----> Launching...
remote:        Released v100
remote:        https://heroku-x-snuffleupagus.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/heroku-x-snuffleupagus.git
   faeb017..7b4a25c  master -> master
```

### Log

```
2020-08-06T16:46:00.721592+00:00 app[web.1]: [06-Aug-2020 16:46:00 UTC] PHP Fatal error:  [snuffleupagus][0.0.0.0][disabled_function][drop] Aborted execution on call of the function 'exec' in /app/public/test/exec.php on line 3
2020-08-06T16:46:00.722278+00:00 app[web.1]: 10.5.233.91 - - [06/Aug/2020:16:46:00 +0000] "GET /test/exec.php?cmd=id HTTP/1.1" 200 186 "-" "curl/7.68.0
2020-08-06T16:46:00.721427+00:00 heroku[router]: at=info method=GET path="/test/exec.php?cmd=id" host=heroku-x-snuffleupagus.herokuapp.com request_id=00000000-1111-2222-3333-444444444444 fwd="1.2.3.4" dyno=web.1 connect=1ms service=4ms status=200 bytes=475 protocol=https
```

**Comment by jvoisin** [comment]
According to [this post]( https://coderwall.com/p/sawjla/get-correct-remote_addr-on-heroku-with-flask ), the headers should be exposed in the environment :/
