### ISSUE TITLE
Add new logger for simulation mode

### ISSUE THREAD

**Issue by wargio** [jvoisin/snuffleupagus#338]
When we log in simulation mode, the log appears to be exactly like the one in non simulation mode.

i suggest then, to add a new logger which adds `[simul]` in the log to make things clearer.

**Comment by jvoisin** [comment]
It looks like a regression due to @kkadosh 's *great logging change*.
I'll try to fix this during this week, and send a PR your way for review.

**Comment by wargio** [comment]
i made a PR on this subject. when you have time, please review it. i'm sure we can find a better way for this.
