### ISSUE TITLE
not working on debian 10 with php7.3

### ISSUE THREAD

**Issue by damnms** [jvoisin/snuffleupagus#343]
not sure if this is supposed to be backward compatible (i only found information about 7.4).
i downloaded the .deb https://github.com/jvoisin/snuffleupagus/releases/download/v0.5.1/snuffleupagus_0.5.1_amd64.deb
installed it, added a 20-snuffleupagus.ini in  /etc/php/7.3/fpm/conf.d as mentioned in the install guide

in the error log i can see:

```
[13-Aug-2020 18:23:41 Europe/Berlin] PHP Warning:  PHP Startup: Unable to load dynamic library 'snuffleupagus.so' (tried: /usr/lib/php/20180731/snuffleupagus.so (/usr/lib/php/20180731/snuffleupagus.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/snuffleupagus.so.so (/usr/lib/php/20180731/snuffleupagus.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

root@server:/etc/php/7.3/fpm/conf.d# find / | grep snuffle
/etc/php/7.4/mods-available/snuffleupagus.ini
/etc/php/7.3/fpm/conf.d/20-snuffleupagus.ini
/var/lib/dpkg/info/snuffleupagus.md5sums
/var/lib/dpkg/info/snuffleupagus.conffiles
/var/lib/dpkg/info/snuffleupagus.list
/usr/share/doc/snuffleupagus
/usr/share/doc/snuffleupagus/changelog.gz
/usr/share/doc/snuffleupagus/README.md.gz
/usr/share/doc/snuffleupagus/copyright
/usr/share/doc/snuffleupagus/examples
/usr/share/doc/snuffleupagus/examples/default.rules.gz
/usr/lib/php/20190902/snuffleupagus.so
/root/snuffleupagus_0.5.1_amd64.deb
```

**Comment by wargio** [comment]
that's weird. the folder is ` /usr/lib/php/20190902/snuffleupagus.so` but the php bin is looking in `/usr/lib/php/20180731/snuffleupagus.so`

**Comment by damnms** [comment]
root@server:/etc# ls /usr/lib/php/201*
/usr/lib/php/20180731:
calendar.so  dom.so   fileinfo.so  gettext.so  imap.so  mbstring.so  mysqlnd.so  pdo_mysql.so  phar.so   readline.so  simplexml.so  sysvmsg.so  sysvshm.so    wddx.so       xml.so        xsl.so
ctype.so     exif.so  ftp.so       iconv.so    json.so  mysqli.so    opcache.so  pdo.so        posix.so  shmop.so     sockets.so    sysvsem.so  tokenizer.so  xmlreader.so  xmlwriter.so

/usr/lib/php/20190902:
snuffleupagus.so

maybe related to the php version, i guess php7.4 uses that /usr/lib/php/20190902 whereas php7.3 uses the 2018 dir

**Comment by damnms** [comment]
when linking i get:
[13-Aug-2020 19:07:55 Europe/Berlin] PHP Warning:  PHP Startup: Unable to load dynamic library 'snuffleupagus.so' (tried: /usr/lib/php/20180731/snuffleupagus.so (/usr/lib/php/20180731/snuffleupagus.so: undefined symbol: php_error_docref), /usr/lib/php/20180731/snuffleupagus.so.so (/usr/lib/php/20180731/snuffleupagus.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Comment by jvoisin** [comment]
The error message is because you didn't compile snuffleupagus against your version of PHP.

**Comment by damnms** [comment]
so the provided binary is incompatible with the official debian repository php version.

**Comment by wargio** [comment]
from what i can see the debs are actually for ubuntu machines.

**Comment by damnms** [comment]
thanks but i have not the time/resources to build it - i thought i give it a try but when there are no builds available for debian, then this project is nothing for me, yet. i will wait until there are debian builds available.
maybe it should be noted, that those builds work _only_ with ubuntu.
tbh i have never seen a productive ubuntu server, but debian.
same with rhel, i have never seen a productive fedora server, but rhel/centos.

**Comment by wargio** [comment]
we can try to add debian builds too.

**Comment by jvoisin** [comment]
I've updated #2 to mention that we should provide debian stable packages as well.

**Comment by wargio** [comment]
@damnms can you try the one i've uploaded? https://github.com/jvoisin/snuffleupagus/releases/tag/v0.5.1

**Comment by damnms** [comment]
worked, thanks
