### ISSUE TITLE
Built in default settings let composer fail

### ISSUE THREAD

**Issue by wedi** [jvoisin/snuffleupagus#348]
**What happened**
composer fails with a strict mode error even when Snuffleupagus is enabled with an empty configuration, i.e. `sp.configuration_file=/dev/null`.

```shell
$ composer
Fatal error: Uncaught TypeError: ini_set() expects parameter 2 to be string, int given in phar:///usr/local/bin/composer/bin/composer:26
Stack trace:
#0 phar:///usr/local/bin/composer/bin/composer(26): ini_set('display_errors', 1)
#1 /usr/local/bin/composer(24): require('phar:///usr/loc...')
#2 {main}
  thrown in phar:///usr/local/bin/composer/bin/composer on line 26
```

**What I have expected**
I would expect that Snuffleupagus does not break anything when there are no rules set.
If this is no bug I would expect to find something when searching for documentation about which rules are enabled by default. If it's there I'd wish for a more prominent pointer to it.

This is true with v0.6.0, v0.5.1 and v0.4.1. Is it a feature and not a bug? If yes, why?

**How to reproduce**

```shell
mkdir composer_test
cd composer_test
cat <<'EOF' > Dockerfile
FROM php:7.4-cli-alpine
COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer
RUN set -eux; \
    echo "sp.configuration_file=/dev/null" > ${PHP_INI_DIR}/conf.d/snuffleupagus.ini; \
    apk --no-cache add pcre pcre-dev; \
    # A lot of lines to download and install snuffleupagus...
    mkdir -p /tmp/snuffleupagus/; \
    curl -fsSL -o /tmp/snuffleupagus/snuffleupagus.tar.gz https://github.com/jvoisin/snuffleupagus/archive/v0.6.0.tar.gz; \
    tar xzf /tmp/snuffleupagus/snuffleupagus.tar.gz --strip-components=1 -C /tmp/snuffleupagus; \
    mkdir -p /usr/src/php/ext/snuffleupagus; \
    cp -a /tmp/snuffleupagus/src/. /usr/src/php/ext/snuffleupagus/; \
    rm -rf /tmp/snuffleupagus; \
    docker-php-ext-install -j$(nproc) snuffleupagus; \
    docker-php-source delete; \
    apk del --no-network pcre-dev;
EOF
docker build -t snuffy .
docker run -ti --rm snuffy composer
```

N.B. This is true with composer 1.10, too.

**Comment by jvoisin** [comment]
Thanks for the detailed bug report, I managed to reproduce the issue on my end, and will investigate tonight

**Comment by jvoisin** [comment]
This should be fixed by e134c87a9a7850d1db30cfe10eb0f521b27953a5

**Comment by jvoisin** [comment]
I also sent a fix upstream to composer: https://github.com/composer/composer/pull/9498

**Comment by jvoisin** [comment]
I added some tests to prevent regressions in 1cb80ae6a095d360bc2988a82468f3d38a876218
