### ISSUE TITLE
Move away from travis-ci

### ISSUE THREAD

**Issue by jvoisin** [jvoisin/snuffleupagus#351]
Travis-ci [won't be free anymore]( https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing ), so we need to either move to github actions, gitlab-ci or anything else that supports different versions of PHP and linux distributions.

**Comment by wargio** [comment]
what about moving to circle ci?

**Comment by jvoisin** [comment]
Or [circle-ci]( https://circleci.com/pricing/ ), I don't care.

**Comment by kpcyrd** [comment]
I'd recommend github actions, they are free and integrate into github pull requests nicely.

**Comment by jvoisin** [comment]
We moved to gitlab-ci instead via b65565a
