### ISSUE TITLE
Mersenne Twister Random number generator (mt_rand) is not an implementation of any form of the Mersenne Twister

### ISSUE THREAD

**Issue by alexanderpas** [jvoisin/snuffleupagus#360]
When calling `mt_rand()` after setting a seed using `mt_srand` when explicitly providing the `MT_RAND_MT19937` as second argument (so we know what we're doing here) the output results do not conform to the Mersenne Twister.

This prevents snuffleupagus to be used on sites which needs any form of deterministic/repeatable random number generation, such as for PHP based puzzle games, where only the seed used to create the puzzle needs to be stored, instead of the complete puzzle.

Additionally, this prevents snuffleupagus to be used in a setup where tests are run, where the input for certain functions needs to be different on each individual call, but the same for each group of calls.

----

PHP Code:

    mt_srand(0xDEADBEF, MT_RAND_MT19937);

    for ($i=0;$i<10;$i++){
        print mt_rand() . "\n";
    }

----

Expected behaviour:

    276364575
    338524641
    516231454
    62768885
    977733109
    229357753
    926345859
    46898234
    1683066362
    1399806165

----

Actual behaviour:

Completely random integers get returned.

----

Notes:

This issue is limited to `mt_rand()` and `mt_srand()` when `mt_srand()` has specifically and explicitly been called using the `MT_RAND_MT19937` contant as second argument.

**Comment by jvoisin** [comment]
Yes, this is a [feature]( https://snuffleupagus.readthedocs.io/config.html#harden-random ) that you can disable via `sp.harden_random.disable();`, see the [documentation]( https://snuffleupagus.readthedocs.io/features.html#weak-prng-via-rand-mt-rand) for more details.

**Comment by alexanderpas** [comment]
The issue is that the replacement of `mt_rand()` is essentially a contract violation of the function name.

However, I agree that if `mt_rand()` is called without explicitly setting the `MT_RAND_MT19937` constant, it might be unintentional, and you might want to do `random_int()` instead, especially considering the behaviour before PHP7.1

At the moment, you can't have `rand()` being an alias for `random_int()` while at the same time, having `mt_rand()` being a implementation of the Mersenne Twister, even if you explicitly call it with the `MT_RAND_MT19937` constant.

This prevents securing third party code which incorrectly uses `rand()` (or maybe even `mt_rand()` without the `MT_RAND_MT19937` constant) while at the same time, being able to use the Mersenne Twister (for example, by calling `mt_rand()` with the `MT_RAND_MT19937` explicitly set.)

**Comment by jvoisin** [comment]
Well, if you're smart enough to want a specific predictable behaviour from your PRNG, odds are that you're smart enough to not misuse `rand` and `mt_rand`, and can safely disabled the PRNG hardening from Snuffleupagus.

Unfortunately, most of the php software _are_ misusing PRNG, hence why the feature is enabled by default.

**Comment by alexanderpas** [comment]
I might be smart enough, and might not be abusing `mt_rand()`, but that doesn't mean third party code is using `rand()` correctly, and I might still want the added benefit of `rand()` being hardened.

**Comment by jvoisin** [comment]
Since `rand` is [an alias]( https://www.php.net/manual/en/migration71.incompatible.php#migration71.incompatible.rand-srand-aliases) to `mt_rand`, this isn't possible

**Comment by wargio** [comment]
can you please describe a situation where having a deterministic `rand` function is useful?

**Comment by alexanderpas** [comment]
Any situation where reproducibility is more important than true randomness.

This includes, but is not limited to:

- Simulations and machine learning. This includes physics simulations and artificial intelligence (AI) in games, as well as simulations to reproduce published research data.
- Monte Carlo estimations.
- Procedural noise generation.
- Games that generate "random" content that is impractical to store.
- Unit tests in which "randomness" ought not to influence whether they pass or fail. Here, a manually-seeded PRNG with a fixed seed is used in place of another kind of RNG for the purpose of the test, to help ensure consistent results across the systems under test, and to allow recording of the seed in case the tests do not pass.

**Comment by wargio** [comment]
i do not see any usage of these in php.

**Comment by jvoisin** [comment]
I concur, those usecases aren't common enough to be worth being supported in Snuffleupagus, sorry.
