### ISSUE TITLE
Broken test suite on alpine

### ISSUE THREAD

**Issue by xXx-caillou-xXx** [jvoisin/snuffleupagus#370]
The test suite is actually broken on alpine using PHP 7.3, with the following results:

```
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   12
---------------------------------------------------------------------

Number of tests :  389               334
Tests skipped   :   55 ( 14.1%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :  104 ( 26.7%) ( 31.1%)
Expected fail   :    3 (  0.8%) (  0.9%)
Tests passed    :  227 ( 58.4%) ( 68.0%)
---------------------------------------------------------------------
Time taken      :   32 seconds
=====================================================================
```

I plan on _trying_ to fix it this week, but should we had commonly used docker image like alpine / debian / centos / ubuntu to the CI to prevent this from happening again ?

**Comment by jvoisin** [comment]
Yes, we need to add distributios to our gitlab-ci.
By the way, you have the commit bit, so you can work by pushing branches in this repository, to trigger gitlab-ci, since it doesn't work (yet?) with external pull-requests.

**Comment by xXx-caillou-xXx** [comment]
It seems like most of the failing tests (72 out of 104) are from PHP 8 but I'm testing using PHP 7.3 and my `PHP_VERSION_ID` is `70325`.
I have no clue why they are being tested.

**Comment by jvoisin** [comment]
I had the very same issue, that I ghetto-fixed like [this]( https://github.com/jvoisin/snuffleupagus/blob/master/.gitlab-ci.yml#L8 ), instead of wasting more time on it :/

**Comment by remicollet** [comment]
Same issue here during RPM build, and same workaround applied.

From a quick search, SKIPIF doesn't work, as extension load fails (bad default config), which remind me an old discussion, "default" config  should be ok.

**Comment by xXx-caillou-xXx** [comment]
I found a ghetto solution using regex on the output

```
--TEST--
Broken configuration
--SKIPIF--
<?php die("skip"); ?>
<?php if (!extension_loaded("snuffleupagus")) print "skip"; ?>
<?php if (PHP_VERSION_ID < 80000) print "skip"; ?>
--INI--
sp.configuration_file={PWD}/config/broken_conf.ini
--FILE--
--EXPECTF--
%r(PHP Fatal error:  \[snuffleupagus\]\[0\.0\.0\.0\]\[config\]\[log\] Invalid configuration prefix for 'this is a broken line' on line 1 in Unknown on line 0

|)%rFatal error: [snuffleupagus][0.0.0.0][config][log] Invalid configuration prefix for 'this is a broken line' on line 1 in Unknown on line 0

Fatal error: [snuffleupagus][0.0.0.0][config][log] Invalid configuration file in Unknown on line 0
Could not startup.
```

We could also use a `%A` instead of the regex, but I'm not sure if this error is the same on other distros.

**Comment by jvoisin** [comment]
Uuugh, just `extends` the `.php7` template in the `.gitlab-ci.yml` file or delete the *php8* files instead of relying on a terrible regexp :/

**Comment by xXx-caillou-xXx** [comment]
Yes, but that would only fix them in the CI, and not really fix the problem. But I can't think of a proper way to fix it.

**Comment by uhlhosting** [comment]
@jvoisin any news? I see the package for alpine is broken.

**Comment by jvoisin** [comment]
The testsuite is working on Alpine.
