### ISSUE TITLE
Add operating systems in the CI

### ISSUE THREAD

**Issue by jvoisin** [jvoisin/snuffleupagus#371]
It would be nice to add:

- [x] debian stable
- [x] latest fedora
- [x] Alpine
  - [x] php8
  - [x] php7
- [x] Archlinux
- [x] latest Ubuntu

**Comment by wargio** [comment]
what about packages for the distros?

**Comment by jvoisin** [comment]
It seems indeed that gitlab-ci can be used to build artifacts, and we should take advantage of this.

**Comment by xXx-caillou-xXx** [comment]
We need to fix these tests for alpine php7 and php8: https://github.com/jvoisin/snuffleupagus/blob/master/.github/workflows/distributions.yml#L102

I couldn't find why they were failing.

**Comment by jvoisin** [comment]
For now, we can simply add as many tests as we can, to avoid regressions, and then investigate.
