### ISSUE TITLE
PHP8 changes parameter names??

### ISSUE THREAD

**Issue by cypherbits** [jvoisin/snuffleupagus#376]
Just installed PHP8 for testing with new compiled Snuffleupagus.
With profile rules like:

`sp.disable_function.function("function_exists").param("function_name").value("eval").drop();
sp.disable_function.function("is_callable").param("var").value("eval").drop();
`

I get the following errors:

`Warning: [snuffleupagus][127.0.0.1][config][log] It seems that you are filtering on a parameter 'var' of the function 'is_callable', but the parameter does not exists. in /var/www/***.php on line 49`

`Warning: [snuffleupagus][127.0.0.1][config][log] It seems that you are filtering on a parameter 'function_name' of the function 'function_exists', but the parameter does not exists. in /var/www/***.php on line 140`

**Comment by wargio** [comment]
@jvoisin this is a really weird behavior.
@cypherbits which version are you using? (write here the commit if possible)

**Comment by cypherbits** [comment]
Well, using master... And php 8.0.2

**Comment by cypherbits** [comment]
Btw, I wanted to enable global strict types but it seems it does not work with Twig templates framework. I opened an issue to them to implement strict types on the project and they say this does not add any security. Is this true? Does strict types does not help security even a little?

**Comment by jvoisin** [comment]
As stipulated in the error message, there is no "var" parameter for [is_callable]( https://www.php.net/manual/en/function.is-callable.php ). Can you try with `value` instead?

Also, can you provide a link to the Twig template issue?

**Comment by cypherbits** [comment]
I will try with value.

Here: 
https://github.com/twigphp/Twig/issues/3489

**Comment by jvoisin** [comment]
There is unfortunately nothing we can do on our side :/

**Comment by cypherbits** [comment]
Hi, I tested again on PHP8 with this other rule:

`sp.disable_function.function("function_exists").param("function_name").value("system").drop();`

I get this error message:

`PHP Warning:  [snuffleupagus][0.0.0.0][config][log] It seems that you are filtering on a parameter 'function_name' of the function 'function_exists', but the parameter does not exists. in /var/www etc...`

**Comment by jvoisin** [comment]
Can you try with `name` instead?

**Comment by cypherbits** [comment]
Nope, 'name' does not exists...

**Comment by jvoisin** [comment]
It seems to be `name` on the [current php master branch]( https://github.com/php/php-src/blob/master/Zend/zend_builtin_functions.c#L1057 ) :/

**Comment by cypherbits** [comment]
Very weird...

**Comment by cypherbits** [comment]
Even ini_set rules are not working.

Are these default rules working for you on PHP8? It worked on 7.4.

**Comment by jvoisin** [comment]
As for `function_exists`, it's now `function` for the function name…

**Comment by jvoisin** [comment]
#379 should help :)

**Comment by cypherbits** [comment]
Many thanks, I will try again.

**Comment by cypherbits** [comment]
Tried and now it is working. 
`is_callable` changed from `var` to `callable_name` too... default rules are broken on PHP8 then...
