### ISSUE TITLE
Is there a switch to disable snuffleupagus?

### ISSUE THREAD

**Issue by andfinally** [jvoisin/snuffleupagus#378]
Snuffleupagus is a super useful library, thanks! I have a small question about configuration. I'm debugging on my local PHP-FPM Docker environment, and I commented out the inclusion of the extension in my `php.ini`

```
;extension=snuffleupagus.so
;sp.configuration_file=/usr/local/etc/snuffleupagus/*.rules
```

But this doesn't seem to have disabled Snuffleupagus completely, because even after rebuilding my containers I get this in my error logs:

```
Warning: [snuffleupagus][0.0.0.0][config][log] No configuration specificed via sp.configuration_file in Unknown on line 0
```

Is there some easy way to disable the extension temporarily?

**Comment by jvoisin** [comment]
You must have enabled snuffleupagus somewhere else in your configuration: it doesn't magically inject itself into your php process :)

**Comment by andfinally** [comment]
Thanks @jvoisin, I'll have another look.
