### ISSUE TITLE
False positive : SQLI protection breaks some webapps (WordPress)

### ISSUE THREAD

**Issue by WhiteWinterWolf** [jvoisin/snuffleupagus#383]
The SQLI protection rules provided as part of the default rules seem highly likely to break lots of webapp.

Here is an example when used with a empty, new WordPress install:

```
security_20210417.log:2021-04-17T23:01:12+02:00 wplmfdc210 snuffleupagus[43885]: [snuffleupagus][0.0.0.0][disabled_function] Aborted execution on call of the function 'mysqli_query', because its argument '$query' content (INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('cron', 'a:2:{i:1618693272;a:1:{s:32:\"recovery_mode_clean_expired_keys\";a:1:{s:32:\"984f690c9015f7b9a17edcaaa9ce9ec0\";a:3:{s:8:\"schedule\";s:5:\"daily\";s:4:\"args\";a:0:{}s:8:\"interval\";i:86400;}}}s:7:\"version\";
```

This error is caused by the following rules which seem very broad IMHO:

```
# sp.disable_function.function("mysqli_query").param("query").value_r("--").drop();
# sp.disable_function.function("mysqli_query").param("query").value_r("#").drop();
# sp.disable_function.function("mysqli_query").param("query").value_r(";.*;").drop();
```

In the current case, the latter one was triggered as WordPress was stores serialized data into the database. I can also easily imagine legitimate cases triggering the other rules.

The issue comes from the fact that these rules do not care about the context surrounding forbidden patterns.

I propose to replace them with such rules which matches forbidden patterns only when they are actually used as SQL statements (ie. outside of strings):

```
sp.disable_function.function("mysqli_query").param("query").value_r("^(?:'(?:\\\\.|[^\\\\'])*+'|[^'])*?;.").drop();
```

Tested on [regex101](https://regex101.com/), this pattern has been tuned to keep low overhead, in particular on non-matching subjects.

Talking about overhead, using a long regular expression is usually way more efficient than using a bunch of smaller ones.

I therefore suggest to replace:

```
# sp.disable_function.function("mysqli_query").param("query").value_r("/\\*").drop();
# sp.disable_function.function("mysqli_query").param("query").value_r("--").drop();
# sp.disable_function.function("mysqli_query").param("query").value_r("#").drop();
# sp.disable_function.function("mysqli_query").param("query").value_r(";.*;").drop();
# sp.disable_function.function("mysqli_query").param("query").value_r("benchmark").drop();
# sp.disable_function.function("mysqli_query").param("query").value_r("sleep").drop();
# sp.disable_function.function("mysqli_query").param("query").value_r("information_schema").drop();
```

With:

```
sp.disable_function.function("mysqli_query").param("query").value_r("^(?:'(?:\\\\.|[^\\\\'])*+'|[^'])*?(?:\\/\\*|--|#|;.|benchmark\\s*\\(|sleep\\s*\\(|information_schema)").drop();
```

The same issue and remarks applies to all database drivers targeted by these rules (`mysql_query`, `mysqli_query` and `PDO::query`).

**Comment by jvoisin** [comment]
Those "anti-sqli" rules were only added as a wink to suhosin, since it implemented this as well, it was never really meant as something serious to deploy into production.

Parsing SQL with regex is a terrible idea, and I'm not sure we want to go this way. Also, about performances, since the regexp are evaluated last when everything else in a rule matches, the performance gains from mashing all of them together is insignificant. 

I removed them and improved the related documentation via 73f764647baa7cdfb66eb6bf4b2feb96e190ef88

**Comment by WhiteWinterWolf** [comment]
OK.

Personally I'll still keep this in my custom rules, as I have the weakness to think it may be useful to tell Snuffleupagus to keep an eye on chained queries and "--" comments and I didn't notice any false positive other negative effects for now (unlike the check for `mysqli_query()` returned value), but I understand you point.
