### ISSUE TITLE
unserialize_hmac breaks some webapps (WordPress)

### ISSUE THREAD

**Issue by WhiteWinterWolf** [jvoisin/snuffleupagus#384]
The `unserialize_hmac` function breaks some webapps like WordPress.

Here is the error raised on fresh, new and empty WordPress install (actually the error prevents to even fully complete the install):

`PHP Fatal error:  Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, string given in ********/wp-includes/class-wp-roles.php:289`

This error is caused by the fact that WordPress actually checks that a string is a valid serialized string before attempting to unserialize it.

This check is done by the `is_serialized()` function defined in *wp-includes/functions.php* which, among other things, check the string last non-blank character:

```
$lastc = substr( $data, -1 );
if ( ';' !== $lastc && '}' !== $lastc ) {
    return false;
}
````

Currently Snuffleupagus relies on what I think to be an undocumented side-effect of the PHP [`unserialize()`](https://www.php.net/manual/fr/function.unserialize.php) function which *"will discard any garbage found at the end of a serialized object, allowing us to simply append a HMAC at the end of strings generated by the serialize, hence guaranteeing that any object deserialized came from the application and wasn’t tampered with"* ([Snuffleupagus documentation](https://snuffleupagus.readthedocs.io/features.html#unserialize-related-magic)).

Doing this *"magic"* breaks any application which check the sanity of serialized data, which is also a good security practice, but is incompatible with `unserialize_hmac`.

IMHO, Snuffleupagus should not rely on such hack, and stick to provide valid serialized data as the output of the `serialize()` function to ensure a maximum stability and reliability.

Currently, when `unserialize_hmac` is enabled, the `serialize()` function would return the following invalid string:

```
a:3:{i:0;i:1;i:1;i:2;i:2;i:3;}23e44818944e62f156276b2b5cc2f8c3587a28c9f87c14830789748beda468cc
```

I suggest to wrap the serialized data and its associated hmac inside a newly serialized string:

```
a:2:{s:7:"sp_data";s:30:"a:3:{i:0;i:1;i:1;i:2;i:2;i:3;}";s:7:"sp_hmac";s:64:"23e44818944e62f156276b2b5cc2f8c3587a28c9f87c14830789748beda468cc";}
```

Note however that Snuffleupagus documentation currently states that the current behaviour allows to disable this feature without invalidating the data, which would not be true anymore with the suggestion above. The feature could still be switched into learning mode with no issue though.

Nevertheless I think that the `unserialize_hmac` is a really powerful protection mechanism, which would gain by being more widely usable.

**Comment by jvoisin** [comment]
This is a conscious tradeoff that was considered during the development of this feature: It's more common to have web applications checking things *after* deserialization than *before*.

We can also argue that it's wordpress doing weird things, since the serialized data is meant to be opaque.

I documented the limitation in 006026b492b119319219cd0e6eb2a6cbdb77c4e6

**Comment by WhiteWinterWolf** [comment]
Fair enough.

> We can also argue that it's wordpress doing weird things, since the serialized data is meant to be opaque.

I must admit I cannot exactly tell why they are checking this. I can think of no concrete security issue avoided this way, and if they are just functionally unsure whether a given string can be unserialized or not then the most sure way is simply to check `unserialize()` returned value.

I guess the next step will be on WordPress side then ;) .

**Comment by WhiteWinterWolf** [comment]
For reference, the issue on WordPress side: <https://core.trac.wordpress.org/ticket/53295>
