### ISSUE TITLE
Add a `notowner_exec` statement to prevent the execution of owned PHP files

### ISSUE THREAD

**Issue by WhiteWinterWolf** [jvoisin/snuffleupagus#387]
I'm not confident in the security brought by the `readonly_exec` statement.

In the classical *nix DAC model, it is expected for unprivileged users to be able to change the *write* permission flag on files they own. Therefore, Snuffleupagus `readonly_exec` statement only relies on the hope that an attacker won't find a way to rely on this standard mechanism to prevent the execution of arbitrary commands on the server.

In practice:

- Web based files manager plugins may allow this action, either explicitly or through a higher level "read-only" or "write protect" checkbox intended to prevent accidental files overwrite.
- Functionalities allowing to extract archives such as *.tar.gz* (which allows to preserve files rights) may also be used to drop writable files on the remote server. Such functionalities can cover functional plugin or theme installation, multiple files upload feature, upgrades, attachments checked server-side, etc.

On the other side, the *nix DAC model has been specifically designed to forbid an unprivileged user to give-away a file to another user by changing its owner. This is a security feature at the core of this model.

In practice, this means that if the webserver runs as the *www-data* user, any created file *will* belong to the *www-data* user. This does not rely on the hope that a framework or webapp may or may not provide a particular feature, it is how the operating system itself has been designed.

Due to this, I suggest the addition of a new statement, `notowner_exec` for instance, which would be quite similar to `readonly_exec` but would instead check that the current process is not owner of the PHP it is about to execute.

The issue #12 already proposed to merge the two features but I think that, as they implement two different checks, they should be kept as two different statements:

- `notowner_exec` alone would be the classical goto on environments where one can use different user accounts to update PHP application and to run the web server.
- `readonly_exec` alone would be a weaker fallback for users with limited access where the same account is used to update the PHP application and to execute it.
- Enabling both settings might be useful in specific cases, for instance different users are used to update the PHP application and to run the web server, but the PHP application may be allowed to concatenate data to some files it doesn't own (a log file, a data file, etc.).

**Comment by jvoisin** [comment]
I agree, it's a good idea. I'll try to implement it when I get the time :)

**Comment by jvoisin** [comment]
@bef what do you think about this?

**Comment by WhiteWinterWolf** [comment]
Having your `readonly_exec.extended_checks()` feature with the possibility, for people who might need it, to fallback the "legacy" `readonly` feature seems a very neat and promising way to handle this, thanks!

**Comment by jvoisin** [comment]
Done via cd90319

**Comment by cypherbits** [comment]
Hello, @jvoisin, is this documented on https://snuffleupagus.readthedocs.io ?

**Comment by jvoisin** [comment]
Nope, thanks for noticing!
I just documented it in 8532f01c7f3c356fbb2dda593477d3902491de77
