### ISSUE TITLE
Eval white and blacklist not working properly

### ISSUE THREAD

**Issue by Cannester** [jvoisin/snuffleupagus#396]
Hello,

I want to disable eval().

When i try simulation mode, system logging as expected

`sp.eval_whitelist.list("strlen").simulation();`

`Jul 12 21:17:10 www snuffleupagus[20272]: [snuffleupagus][X.X.X.X][Eval_whitelist][simulation] The function 'shell_exec' isn't in the eval whitelist, logging its call. in /usr/local/lsws/DEFAULT/html/test.php(7) : eval()'d code on line 1`

When i remove simulation, its dropping all functions in the codes;

`Jul 12 20:57:41 www snuffleupagus[18204]: [snuffleupagus][69.162.124.236][Eval_whitelist][drop] The function 'getLoader' isn't in the eval whitelist, dropping its call. in /path/autoload_real.php on line 16`

This is a normal php function;

`line 16:     public static function getLoader()
`

**Comment by jvoisin** [comment]
This is the expected behaviour: if you only whitelist `strlen`, no other function can be called in an `eval`, including user-defined ones.
