### ISSUE TITLE
Allow more character per line in our code style

### ISSUE THREAD

**Issue by jvoisin** [jvoisin/snuffleupagus#398]
@bef raised that the issue that since we're 2021, we should have more than 80 chars per line:

Currently, we're using/recommending this:

```
clang-format -i --style="{BasedOnStyle: google, SortIncludes: false}" src/*.[hc]
```

it would be nice to allow larger lines.

**Comment by wargio** [comment]
just create a clang format style.

https://github.com/rizinorg/rizin/blob/dev/.clang-format#L12

**Comment by bef** [comment]
I suggest that we just allow longer lines without actually enforcing them. In some cases line breaks can significantly improve readability.

My main issue was, that line based searches over the code, e.g. with grep or most IDEs, will not have the desired result set. For example, searching for `sp_log.*\("config"` to get all the log calls with argument 1 being "config" will not work when `"config"` is located in the next line.

**Comment by jvoisin** [comment]
@bef how do you feel about `clang-format -i --style="{BasedOnStyle: google, SortIncludes: false, ColumnLimit: 0}" src/*.[hc]` ?

**Comment by bef** [comment]
This makes the code a lot more consistent in most cases. I do however have a few remarks:

Indices get wrapped into the next line in combination with macros like so
```
-    ZSTR_VAL(ret)[len] = 0;
+    ZSTR_VAL(ret)
+    [len] = 0;
```

Same for incrementing/decrementing with macros
```
-  SPG(execution_depth)--;
+  SPG(execution_depth)
+  --;
```

Indentations after ZEND_HASH_FOREACH_* get lost.

Some files should be excluded:
* sp_config_scanner.c / sp_config_scanner.cached.c (autogenerated code)
* tweetnacl.* (original versions, which are easier to compare if unchanged)
* sp_php_compat.* (in part copy/paste versions of original PHP functions / easier to compare if left unchanged)

@jvoisin If it's ok with you I would much rather consider clang-format changes as a suggestion and not strictly enforce them for now.

**Comment by jvoisin** [comment]
I wasn't planning on enforcing anything before everyone is happy with the suggested code style :)
