### ISSUE TITLE
How to disable Eval fucntion but enable it for Phar

### ISSUE THREAD

**Issue by closte** [jvoisin/snuffleupagus#400]
# Output:
```
[~]$ wp search-replace 'one' 'two' --all-tables
Fatal error: [snuffleupagus][0.0.0.0][disabled_function][drop] Aborted execution on call of the function 'eval' in phar:///usr/bin/wp-source/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code on line 6
```

# Config:

```python
sp.wrappers_whitelist.list("phar");

# Prevent `system`-related injections
sp.disable_function.function("system").drop();
sp.disable_function.function("shell_exec").drop();
sp.disable_function.function("exec").drop();
sp.disable_function.function("proc_open").drop();
sp.disable_function.function("eval").drop();
sp.disable_function.function("passthru").drop();
```

# Tried:

> Whitelisting the line number
> Whitelisting the file name
> Whitelisting the PHAR

**Comment by wargio** [comment]
probably you can whitelist it via `filename_r`.
try `sp.disable_function.function("eval").filename_r("^phar://.+$").allow();` by placing it before the drop (*not tested*).

**Comment by closte** [comment]
> probably you can whitelist it via `filename_r`.
> try `sp.disable_function.function("eval").filename_r("^phar://.+$").allow();` by placing it before the drop (_not tested_).

I tried but its the same error message:

`Fatal error: [snuffleupagus][0.0.0.0][disabled_function][drop] Aborted execution on call of the function 'exec' in phar:///usr/bin/wp/vendor/wp-cli/php-cli-tools/lib/cli/Shell.php on line 53`

Here is the config file:

```
# Prevent `system`-related injections
sp.disable_function.function("eval").filename_r("^phar://.+$").allow();
sp.disable_function.function("system").drop();
sp.disable_function.function("shell_exec").drop();
sp.disable_function.function("exec").drop();
sp.disable_function.function("proc_open").drop();
sp.disable_function.function("eval").drop();
sp.disable_function.function("passthru").drop();
```

Any more tips?

**Comment by wargio** [comment]
maybe is a bug

**Comment by closte** [comment]
> maybe is a bug

What about changing the "snuffleupagus support => enabled" value when executing a PHP CLI command, something like:

`/usr/bin/php -d snuffleupagus_enabled=false /index.php`

**Comment by jvoisin** [comment]
You got two different messages: The first time, it was about `eval`, the second one is about `exec`, so you might need to allow `eval` **and** `exec` in your *phar* files.

Also, there is no need to add `.+$` to your regex :)
