### ISSUE TITLE
Rules for include and require do not work in PHP 8.1

### ISSUE THREAD

**Issue by jeriedel24** [jvoisin/snuffleupagus#403]
While testing PHP 8.1 RC5 with snuffleupagus (using the default ruleset fpr PHP 8) I noticed that all calls of the statements "include" or "require" are dropped. The exception in snuffleupagus.rules that allows to include files with suffix ".inc" or ".phtm" or ".php" to be included does not work. It works as expected in PHP 8.0.12. I am using snuffleupagus 0.7.1. Tested with RHEL 8 and with Solaris 10.

**Comment by jeriedel24** [comment]
The findings are the same when testing with PHP 8.1.1 (on Solaris 10 and on RHEL 8).
I am waiting for issue #405 to be dealt with.

**Comment by cypherbits** [comment]
Seems like PHP likes to change parameter names a lot. This happens on every new release... Maybe we could use parameter position instead of name?? @jvoisin

**Comment by iio7** [comment]
I can confirm this.

I have just compiled and installed the latest snuffleupagus for PHP 8.1.3 on OpenBSD current.

I have the following rules:

```
sp.disable_function.function("require_once").value_r("\.(php)$").allow();
sp.disable_function.function("include_once").value_r("\.(php)$").allow();
sp.disable_function.function("require").value_r("\.(php)$").allow();
sp.disable_function.function("include").value_r("\.(php)$").allow();
sp.disable_function.function("require_once").drop()
sp.disable_function.function("include_once").drop()
sp.disable_function.function("require").drop()
sp.disable_function.function("include").drop()
```
A require statement for a `.php` file gets dropped:

```
PHP message: PHP Fatal error:  [snuffleupagus][0.0.0.0][disabled_function][drop] Aborted execution on call of the function 'require' in /htdocs/foo.example.com/public/index.php on line 3
```

**Comment by iio7** [comment]
What is the project priority for fixing this?

Snuffleupagus should not make the mistake as so many projects do by focusing too much on backwards compatibility which then puts the project in a deadlock because upstream are changing too many things. Let snuffleupagus support only the latest release from PHP and then make sure it always works on that.

**Comment by jvoisin** [comment]
Here is the short/medium plan, for me:

1. recovering from COVID
2. trying to merge [SektionEins' work]( https://github.com/sektioneins/snuffleupagus ) without breaking too many things.
3. do a release
4. port to php 8.1 :)

**Comment by jeriedel24** [comment]
I have tested snuffleupagus 192a24a with PHP 8.1.4. This version of snuffleupagus identifies itself as "0.8.0-sng" in the output of phpinfo().
Great work!
The standard ruleset now works with PHP 8.1. In particular the exceptions for include and require now work.
It also works with PHP 7.4.28.
Tested on RHEL 7.0, RHEL 8.0, RHEL 9.0 Beta.
Tests on Solaris 10 and on Solaris 11 are still pending.
