### ISSUE TITLE
Use calltrace hash to limit dumps() instead of a hash of the rule

### ISSUE THREAD

**Issue by jvoisin** [jvoisin/snuffleupagus#412]
Instead of having one dump per rule, we should have one dump per hash of the calltrace who triggered the rule.

Cc: @zetatwo

**Comment by laluka** [comment]
I woule LOVE to have this, or usine the timestamp of the received request, anything that would allow to have many dumps to grep !

The idea of the stacktrace's hash is nice for unicity, but I'm a bit scared about the overhead this could introduce..
Maybe just a CRC? Or a very light & fast hash?

**Comment by wargio** [comment]
it is easier to just generate a uuid or similar.

**Comment by jvoisin** [comment]
An uuid won't fly, since we're using deduplication to prevent attackers from filling the filesystem. A stacktrace hash shouldn't have any noticeable overhead, since it'll only be triggered when a rule is matched.

**Comment by jvoisin** [comment]
Done in 3dbb2f3

I did some simple profiling, and the sha256 computation isn't really a bottleneck. Worse case, we can always move to adler32 or crc32 should it become one.
