### ISSUE TITLE
Where Almalinux / CentOS installation?

### ISSUE THREAD

**Issue by SametChan** [jvoisin/snuffleupagus#414]
Hello,

I am unable to find one Almalinux or CentOS installation from the download page, I am only seeing the Debian or Ubuntu available. Is there a way to where installation is?

**Comment by wargio** [comment]
we did not create them.

**Comment by wargio** [comment]
I guess is possible. @jvoisin i really need to write down the CI code for building the releases.

**Comment by SametChan** [comment]
> I guess is possible. @jvoisin i really need to write down the CI code for building the releases.

If you do that, that would be appreciated! I could donate to you $10 Euro :)

**Comment by jvoisin** [comment]
Snuffleupagus is packaged in RHEL and Fedora by @remicollet

**Comment by remicollet** [comment]
@SametChan see https://rpms.remirepo.net/wizard/
