### ISSUE TITLE
Version 0.8.0 reports 0.9.0

### ISSUE THREAD

**Issue by remicollet** [jvoisin/snuffleupagus#418]
Because:

`#define PHP_SNUFFLEUPAGUS_VERSION "0.9.0"
`

**Comment by wargio** [comment]
did you use a deb file?

**Comment by remicollet** [comment]
No, build from sources (from the tag) to build the RPM

**Comment by remicollet** [comment]
So: https://github.com/jvoisin/snuffleupagus/blob/v0.8.0/src/php_snuffleupagus.h#L4

**Comment by wargio** [comment]
yes, i saw. so we have this issue also oon the debs. :/

**Comment by remicollet** [comment]
Notice RPM are OK, version is checked before the build, so I report this issue, fix the version, and build the packages with proper value ;)

**Comment by jvoisin** [comment]
Shall we release a 0.8.1 to address this?

**Comment by wargio** [comment]
probably a good idea.

**Comment by jvoisin** [comment]
I'll do one tonight then :)
