### ISSUE TITLE
undocumented breaking change

### ISSUE THREAD

**Issue by duritong** [jvoisin/snuffleupagus#420]
Since 0.8.0 the keyword disable_xxe was replaced with 713cb08b58d4e5dd5e7e80b1f82e27cbe52d4381 - However, if you just upgrade to 0.8.0 with an existing config, your php process will crash (and with FPM actually quite hidden when being forked from the master process) with the following message:

```
NOTICE: sapi_cgi_log_message(), line 618: PHP message: PHP Fatal error:  [snuffleupagus][0.0.0.0][config][log] Unexpected keyword 'disable_xxe' on line 5 in Unknown on line 0
```

The effect is that php-fpm is just busy trying to spawn new php processes without any notice or logs.

It would be good to document such breaking changes in release notes, but it can't be found in this repo nor on the release notes: https://dustri.org/b/snuffleupagus-080-woolly-mammoth.html

**Comment by jvoisin** [comment]
You are absolutely right, it should have been documented, lesson learned, thanks!

It's now documented in this repo, on the blogpost, and in the github changelog.
