### ISSUE TITLE
Different behavior for eval & system

### ISSUE THREAD

**Issue by laluka** [jvoisin/snuffleupagus#427]
Similar to https://github.com/jvoisin/snuffleupagus/issues/426 but explained in a (I hope) clearer way.. :)

So, here's the thing, `eval` and `system` don't have the same behavior, which makes it hard to rely on for audit/fuzz purpose. 

For system, the `simulation` works great, by logging only the function name (call 1) or a detailed version with a wildcard on `param_r` : 
![image](https://user-images.githubusercontent.com/7013722/176907352-608427d4-4fc1-4290-9bf6-a086bd271d12.png)

For eval, the `simulation` works well for the function log call, but no details of the eval'd code even with param_r : 
![image](https://user-images.githubusercontent.com/7013722/176907651-78269edc-b776-485d-9eb9-f06e961eb946.png)

It would be awesome to have a way to get the eval'd code dumped while using simulation, to not rely on the .dump() feature that writes to the filesystem instead of the main picked logger...

I hope this explained a bit better the use-case I'm facing! :)
Once again, thanks for the awesome work! :tulip: :heart_decoration:

**Comment by jvoisin** [comment]
Done in 423e133
