### ISSUE TITLE
sp.ini_protection.enable(); can't be enabled

### ISSUE THREAD

**Issue by PanosPetrou** [jvoisin/snuffleupagus#428]
Hello,

I have a DirectAdmin server, running multiple versions of PHP (5.6, 7.4, 8.1) as php-fpm.

Every time I try to enable `sp.ini_protection.enable();` I get:

```
PHP Fatal error:  [snuffleupagus][0.0.0.0][config][log] Invalid configuration section 'sp.ini_protection.enable();' on line 2 in Unknown on line 0
PHP Fatal error:  [snuffleupagus][0.0.0.0][config][log] Invalid configuration file in Unknown on line 0
```

I have configured the extensions as:

```
extension=snuffleupagus.so
sp.configuration_file=/usr/local/php81/lib/php.conf.d/*.rules
```

And I'm using the rules:
- `default_php8.rules`
- `ini_protection.rules`

**Comment by jvoisin** [comment]
Could it be the same problem as in #425 ?

**Comment by bef** [comment]
Hi. Thank your for reporting your snuffleupagus issue. It seems, that your are trying to match a parameter called `function_name` for `function_exists()`. In PHP8 the parameter name changed and is now known as `function`. In order to avoid the issue (apart from commenting out the actual error message in the source code) you can either change the parameter name to `function` or match by position, e.g. `.pos("0")`.

**Comment by PanosPetrou** [comment]
> Hi. Thank your for reporting your snuffleupagus issue. It seems, that your are trying to match a parameter called `function_name` for `function_exists()`. In PHP8 the parameter name changed and is now known as `function`. In order to avoid the issue (apart from commenting out the actual error message in the source code) you can either change the parameter name to `function` or match by position, e.g. `.pos("0")`.

Interesting, thank you for letting me know.

**Comment by bef** [comment]
> Interesting, thank you for letting me know. Is it possible, while using the same rules file, to use a condition or something, to load specific rules for PHP 8 and others for PHP 7?

I'm so glad you asked. Since Snuffleupagus version 0.8 you can declare conditional rules like so:
```
@condition PHP_VERSION_ID < 80000;
some rules
@condition PHP_VERSION_ID >= 80000;
some other rules
@end_condition;
```

**Comment by PanosPetrou** [comment]
Oh that's really nice
Thanks bef

**Comment by jvoisin** [comment]
I just documented this in e5b8308f4572cd4f70a0c4f1e3640c4213b77079
