### ISSUE TITLE
It seems zend.exception_string_param_max_len is not recognized

### ISSUE THREAD

**Issue by PanosPetrou** [jvoisin/snuffleupagus#430]
In my environment `zend.exception_string_param_max_len` is set to `0` in my php.ini.

I get frequent php warnings such as:

```
PHP Warning:  [snuffleupagus][0.0.0.0][ini_protection][log] Cannot hook INI var `zend.exception_string_param_max_len` Maybe a typo or the PHP extension providing this var is not loaded yet. in Unknown on line 0
```

**Comment by jvoisin** [comment]
You might want to comment the `sp.ini.key("zend.exception_string_param_max_len").ro();` line in the `config/ini_protection.rules`, since it sets this configuration variable as read-only.
