### ISSUE TITLE
Compatibility with OPcache JIT

### ISSUE THREAD

**Issue by Tristan971** [jvoisin/snuffleupagus#441]
Trying to enable the OPcache JIT results in the following runtime notice:
> NOTICE: PHP message: PHP Warning:  JIT is incompatible with third party extensions that override zend_execute_ex(). JIT disabled. in Unknown on line 0

While the message isn't particularly clear, I believe it's safe to assume that it is about

https://github.com/jvoisin/snuffleupagus/blob/c016fa1a7ce11e657f215dd69deac59d973d6dd9/src/sp_execute.c#L386-L391

By the looks of it (from https://github.com/newrelic/newrelic-php-agent/issues/223#issuecomment-910303462) it would seem that this behaviour dates back from PHP 8.0.1.

While I don't expect this can be "fixed" by design, I could be wrong as I'm not that familiar with Zend engine's internals; so this issue can serve at least as an answer to other people.

(For what it's worth, having compared JIT vs non-JIT performance on our main backend, we saw between no change and even slightly-averse performance anyway, so it's not a big deal for us; I was just giving it another try since it'd been a while and this is for a very different other application)

**Comment by jvoisin** [comment]
Yeah, I don't think that the JIT would be too happy with our functions hooking shenanigans :/

**Comment by Tristan971** [comment]
Makes sense 👍
