### ISSUE TITLE
Multiple cookie SameSite enforcement through regex

### ISSUE THREAD

**Issue by thiekus** [jvoisin/snuffleupagus#449]
Hi, I'm currently use snuffleupagus on wordpress web server that handle about a hundred university departments wordpress websites to prevent another injection. Works fine after tweakings and so effective in my test, but I have question.

Is possible to set `SameSite` with regex instead of name, just like `name_r()` or `filename_r()` for `disable_function()`, since wordpress usually have different cookie name for different website (example is wordpress_logged_in_<some_hash> to store login information, which differ for each sites). Reason is to prevent possible credentials hijacking through CSRF and as some department web admins were too lazy to secure their website (routine maintenance or sometimes install vulnerable plugins).

Thanks!

**Comment by jvoisin** [comment]
It [should already work]( https://github.com/jvoisin/snuffleupagus/blob/master/src/sp_config.h#L67 ) with `name_r`.

**Comment by thiekus** [comment]
Nice, it works as expected. AFAIK, It didn't mentioned in cookies configuration before so I didn't know if this possible. Anyway, thank you for this project!
