### ISSUE TITLE
Error after loading 0.9.0 version compiled on php 7.3.33 zts.

### ISSUE THREAD

**Issue by cryptobob** [jvoisin/snuffleupagus#450]
/usr/lib64/php-zts/modules/snuffleupagus.so: undefined symbol: compiler_globals)) in Unknown on line 0

**Comment by remicollet** [comment]
What distribution is that ? version ? PHP provider ?

From layout, looks like a **RPM**, so probably from "remi" repository, in which case you should use the **php-snuffleupagus** package from the same provider.

**Comment by cryptobob** [comment]
remi php-7.3.33-1.el7.remi.x86_64 but that works on NTS and not on ZTS

**Comment by cryptobob** [comment]
I manually compiled the latest version still getting the same error. Also
/usr/bin/zts-php --define extension=$PWD/modules/snuffleupagus.so --define sp.allow_broken_configuration=1 --modules | grep snuffleupagus
snuffleupagus
snuffleupagus
*** Error in `/usr/bin/zts-php': double free or corruption (!prev): 0x00005605f59cc5a0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81679)[0x7f3dfea1e679]
/usr/bin/zts-php(ts_free_id+0xc5)[0x5605f552fbd5]
/usr/bin/zts-php(+0xf0aae)[0x5605f5389aae]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f3dfe9bf505]
/usr/bin/zts-php(+0xf0d87)[0x5605f5389d87]

**Comment by remicollet** [comment]
BTW, why are you using ZTS build ?

**Comment by remicollet** [comment]
RPM doesn't provides the ZTS extension because it is not supported, see  #123

**Comment by jvoisin** [comment]
*Fixed* by #451
