### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by armory86** [jvoisin/snuffleupagus#455]
Hi, can you help me? I'm triying to install on Debian `bullseye` php 8.2.7 from [packages.sury.org](https://packages.sury.org/php/)

```bash
Disable functions - die [tests/disable_function/disabled_functions_die.phpt]  XFAIL REASON: 
Disable functions - exit [tests/disable_function/disabled_functions_exit.phpt]  XFAIL REASON:
```
`curl` 7.88.1
`libxml` 2.9.14

Both are enabled, even can't install .deb package.

**Comment by jvoisin** [comment]
The complete message being:

```
EXPECTED FAILED TEST SUMMARY
---------------------------------------------------------------------
Disable functions - die [tests/disable_function/disabled_functions_die.phpt]  XFAIL REASON: 
Disable functions - exit [tests/disable_function/disabled_functions_exit.phpt]  XFAIL REASON: 
=====================================================================
```

so this is absolutely expected.

**Comment by armory86** [comment]
Can you please, give me some directions?

**Comment by jvoisin** [comment]
Directions for what?

**Comment by wargio** [comment]
> Can you please, give me some directions?

The tests are expected to fails because they invoke die and exit.
