### ISSUE TITLE
.deb doesn't ship PHP8 rules

### ISSUE THREAD

**Issue by mdPlusPlus** [jvoisin/snuffleupagus#458]
.deb 0.9.0

`/usr/share/doc/snuffleupagus/examples/` only contains the PHP7 `default.rules.gz`.

I'm not an experienced debian packager, but my guess is https://github.com/jvoisin/snuffleupagus/blob/master/debian/snuffleupagus.examples has to be modified to ship both files.

**Comment by jvoisin** [comment]
Should be fixed by d08eef0
