### ISSUE TITLE
none-standard symbols brake executions of rules

### ISSUE THREAD

**Issue by dimitargi** [jvoisin/snuffleupagus#464]
It looks like that when a file with rules contains some special symbols in it like this one `…` all other rules after the line where the symbol is are just discarded and not evaluated.

if you look at the example on this page https://snuffleupagus.readthedocs.io/config.html#miscellaneous-examples the symbol is part of below line just between chdirs

 ```
ini_set('open_basedir','..');chdir('..');…;chdir('..');ini_set('open_basedir','/');echo(file_get_contents('/etc/passwd'));
```

same behaviour for this character as well `’` even when is in a comment

latest release of snuffleupagus compiled from source, CentOO9, php 8.2.10+fpm on Apache

**Comment by jvoisin** [comment]
Only ascii is supported in the rules.

**Comment by jvoisin** [comment]
Documented in f672fa5
