### ISSUE TITLE
upgrading from older versions to latest

### ISSUE THREAD

**Issue by VedranIteh** [jvoisin/snuffleupagus#465]
I would like to upgrade from 0.3.0. (Dentalium elephantinum) to the latest version.
Except "Breaking changes" to be corrected in the conf files, is there anything else to watch out for ?
directory structures, new/renamed conf files, etc.?

Is there an official upgrade script or procedure or just delete/reinstall ? 

Thx,
Vedran

**Comment by jvoisin** [comment]
Some functions parameters names might have changed, since PHP likes to renamed them from time to time, otherwise, there is nothing I can think of.

To upgrade, you can simply replace the .so, restart php and you should be good to go.
