### ISSUE TITLE
Snuffleupagus for php 7.4 latest

### ISSUE THREAD

**Issue by barianto2007** [jvoisin/snuffleupagus#467]
What best version snuffleupagus for php 7.4 latest

using branch barbar the elepant got thie error when loaded on php "

`/usr/lib/php/20190902/snuffleupagus.so: undefined symbol: __zend_strdup)`

using branch elephant gambit (0.8.3) got thie error when loaded on php "

`(/usr/lib/php/20190902/snuffleupagus.so: undefined symbol: PHP_SHA256InitArgs)`

Please Help

**Comment by jvoisin** [comment]
It looks like you need to compile snuffleupagus against the php version you're using.

**Comment by barianto2007** [comment]
Okay, I will try.

Currently, it works using binary from GitHub for branch 0.6.0, but rules syntax differently with the latest branch which needs another learning curve since I also use snuffleupagus latest for php8.2.

Thanks.
