### ISSUE TITLE
Patchstack Wordpress Vulnerability DB

### ISSUE THREAD

**Issue by nickchomey** [jvoisin/snuffleupagus#480]
Patchstack is arguably the leading WP security program/service, and their main role is to issue vPatches - fixes for vulnerabilities found through their bug bounty program, prior to the plugin developers providing a fix for it. 

They have a comprehensive Vulnerability Database and I'm wondering if it could be useful for further development and testing of snuffleupagus, by showing new and/or popular vulnerabilities? (To be clear, I'm not saying you should fix plugin issues - just perhaps find common issues that could have been fixed by generic snuffleupagus rules.

I hope this helps!

https://patchstack.com/database/

And an API https://patchstack.com/threat-intel-feed/

**Comment by jvoisin** [comment]
Unfortunately, they don't provide any details about vulnerabilities, so their website is kinda useless.
