### ISSUE TITLE
Support for PHP 8.3 on Alpine Linux 

### ISSUE THREAD

**Issue by essovius** [jvoisin/snuffleupagus#489]
I'm trying to install the `php83-snuffleupagus` package on my Alpine Linux system (version 3.19), but I'm unable to find it in the official Alpine Linux repositories or any of the community repositories I have enabled. 

I've tried searching the Alpine Linux package lists and forums, but I can't find any information about this package or why it might be missing. I've also tried enabling additional community repositories, but the package is still not found.

https://pkgs.alpinelinux.org/packages?name=php83-snuffleupagus&branch=v3.19&repo=&arch=x86_64&maintainer=

Any help or guidance on how to install this package or find more information about its availability would be greatly appreciated.

**Comment by jvoisin** [comment]
It means that Snuffleupagus isn't packaged in Alpine Linux, meaning that you'll have to install it [manually](https://snuffleupagus.readthedocs.io/installation.html)
